### ISSUE TITLE
Failed to install on 11.6 OS X

### ISSUE THREAD

**Issue by domainator** [HandyOSS/HandyHost#1]
Version: HandyHost_v0.4.8.pkg
Installer fails to install the package.
Pre-requisites seem to be fine.
1. From cmd line: xcode-select: error: command line tools are already installed, use "Software Update" to install updates
2. From the log: 2021-10-07 09:06:46+03 _<laptop-name>_ package_script_service[39494]: ./postinstall: ******* HOMEBREW IS REQUIRED, EXITING ***********
Output of "brew -v":
Homebrew 3.2.15
Homebrew/homebrew-core (git revision d584dfd8b61; last commit 2021-10-07)
3. Docker I've installed a while ago from the official website (not from homebrew) - shouldn't be an issue, right?

From UI perspective it breaks on "Validating Packages..."

tail -f /var/log/install.log:
2021-10-07 09:06:46+03 _<laptop-name>_ installd[627]: PackageKit: Install Failed: Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “HandyHost_v0.4.8.pkg”." UserInfo={NSFilePath=./postinstall, NSURL=file://localhost/Users/_<username>_/Downloads/HandyHost_v0.4.8.pkg, PKInstallPackageIdentifier=com.HandySoftware.pkg.HandyHost, NSLocalizedDescription=An error occurred while running scripts from the package “HandyHost_v0.4.8.pkg”.} {
	    NSFilePath = "./postinstall";
	    NSLocalizedDescription = "An error occurred while running scripts from the package \U201cHandyHost_v0.4.8.pkg\U201d.";
	    NSURL = "file://localhost/Users/_<username>_/Downloads/HandyHost_v0.4.8.pkg";
	    PKInstallPackageIdentifier = "com.HandySoftware.pkg.HandyHost";
	}
2021-10-07 09:06:46+03 _<laptop-name>_ installd[627]: PackageKit: Running idle tasks
2021-10-07 09:06:46+03 _<laptop-name>_ Installer[39460]: install:didFailWithError:Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “HandyHost_v0.4.8.pkg”." UserInfo={NSFilePath=./postinstall, NSURL=file://localhost/Users/_<username>_/Downloads/HandyHost_v0.4.8.pkg, PKInstallPackageIdentifier=com.HandySoftware.pkg.HandyHost, NSLocalizedDescription=An error occurred while running scripts from the package “HandyHost_v0.4.8.pkg”.}

**Comment by domainator** [comment]
Update: Installing XCode did not change behavior of the installer. Still fails with the same error.

**Comment by domainator** [comment]
Tried v.0.5.0 - the same issue

**Comment by alexsmith540** [comment]
Can you run the following command for me? It seems like homebrew is installed on your system, maybe not linked up to your $PATH environment variable. 
```command -v brew``` or ```ls /usr/local/bin``` (and see if theres a file called "brew")
If indeed we find ```/usr/local/bin/brew``` then we have installed it. In which case, an interim fix will be running this command:
```echo "export PATH=/usr/local/bin:$PATH" >> ~/.bash_profile```
and then run the installer again. 
Hopefully this fixes it up (and helps me tune that "which brew" command in macos..)

**Comment by domainator** [comment]
I did it and now installer proceeds further. Now it is downloading cosmos-sdk and doing some other stuff. Thanks a lot! If you need me to run any other command to help to integrate the fix into the release, please let me know.

**Comment by domainator** [comment]
Failed again after building packages. What I see right now at the end of the log:
`./postinstall:   build/temp.macosx-10.14-x86_64-3.8/_openssl.c:575:10: fatal error: 'openssl/opensslv.h' file not found`
`./postinstall:   ERROR: Failed building wheel for cryptography`
`./postinstall: fatal: empty string is not a valid pathspec. please use . instead if you meant to match all paths`
`./postinstall: /tmp/PKInstallSandbox.opN4sz/Scripts/com.HandySoftware.pkg.HandyHost.1bRa38/postinstall: line 395: platypus: command not found`
`./postinstall: /tmp/PKInstallSandbox.opN4sz/Scripts/com.HandySoftware.pkg.HandyHost.1bRa38/postinstall: line 414: node: command not found
`

**Comment by domainator** [comment]
Launched again and in the very beginning I see:
```
./postinstall: installing akash dependencies...
./postinstall: -bash: brew: command not found
./postinstall: Installing Kubectl...
./postinstall: -bash: brew: command not found
./postinstall: /tmp/PKInstallSandbox.14olQD/Scripts/com.HandySoftware.pkg.HandyHost.9Xf1Kw/postinstall: line 274: jq: command not found
...
./postinstall: fatal: empty string is not a valid pathspec. please use . instead if you meant to match all paths
./postinstall: /tmp/PKInstallSandbox.14olQD/Scripts/com.HandySoftware.pkg.HandyHost.9Xf1Kw/postinstall: line 298: virtualenv: command not found
./postinstall: /tmp/PKInstallSandbox.14olQD/Scripts/com.HandySoftware.pkg.HandyHost.9Xf1Kw/postinstall: line 299: venv/bin/activate: No such file or directory
```

**Comment by alexsmith540** [comment]
Hm ok maybe your system isn't using .bash_profile by default? The 'brew:command not found' errors seem to think so anyway..
Can you ```ls -la ~``` and see if a file called .zshrc, .zprofile, or .profile exist?
Also can you try to run:
```brew install jq```
and see if it installs dependencies correctly?

**Comment by domainator** [comment]
`brew install jq` went fine
None of the mentioned files are in the directory

**Comment by domainator** [comment]
Then I did the same for `golang`, `nvm` and a few others and somehow managed to complete installation. However, I see this in the status bar:

<img width="652" alt="Screenshot 2021-11-07 at 22 58 37" src="https://user-images.githubusercontent.com/84642046/140659919-d126f82f-23d2-4b21-a23d-bebc99c37572.png">

**Comment by alexsmith540** [comment]
I tried a few things and really hoping I have the issue solved. When you get a chance, I added a new pkg installer called
HandyHost_v0.5.0.1-rc0.macos.zsh.pkg to the release at https://github.com/HandyOSS/HandyHost/releases/tag/v0.5.0
Thanks again for the help and patience, appreciate it a ton.

**Comment by domainator** [comment]
This time it installed and I don't see any messages in the status panel. However there is still some strange backtrace present in the install log. I don't know if it impacts anything, so attaching the whole log.
[0.5.0.1-rc0.txt](https://github.com/HandyOSS/HandyHost/files/7494453/0.5.0.1-rc0.txt)

And there are also a few entries of
`./postinstall: -bash: brew: command not found`

**Comment by alexsmith540** [comment]
Cool the full log helped a ton, thanks! For whatever reason when the installer is running the ```brew install``` commands it's not finding the brew path, like its either not sourcing .bash_profile or .zshrc for the commands run with su - notrootuser -c "brew install ...". So I basically gave any brew install command the full path to brew so hopefully the HandyHost_v0.5.0.1-rc1.macos.zsh.pkg installer I just uploaded should (finally) fix up any missing brew dependencies.

**Comment by domainator** [comment]
In the process of installing things, but I already see:
`-bash: /usr/local/brew: No such file or directory` in the logs
Should it be `/usr/local/bin/brew` as `where` command points to?

**Comment by alexsmith540** [comment]
Indeed. Test threw no errors ofc, sorry about that 🤦..  I just updated with HandyHost_v0.5.0.1-rc2.macos.zsh.pkg

**Comment by domainator** [comment]
Here is the log:
[0.5.0.1-rc2.txt](https://github.com/HandyOSS/HandyHost/files/7495165/0.5.0.1-rc2.txt)
Apparently, the behavior was different this time and it downloaded more stuff. I found one place where it did not find `brew` again, in the very beginning when tried to update `brew`. At the end there is stack trace, don't know how problematic it is. Thanks!
