### ISSUE TITLE
trying to start akash provider. this error message follows

### ISSUE THREAD

**Issue by Supernaut90** [HandyOSS/HandyHost#11]
"Starting Akash Provider... expect: spawn id exp3 not open while executing "expect eof" (file "./runProviderAutomated.sh" line 23)"

If anyone can shed some light on where i messed up and what i can do to fix this will be greatly appreciated.

if you need more information please let me know what you need; im very new to all of this and am totally out of field here.

**Comment by alexsmith540** [comment]
Couple of questions:
1. Do you happen to have a space character in your wallet key? Reason being that I ran into a regression a few days ago with this specific script and a space character in the wallet name, wondering if that’s the same case here.
2. If not: just confirming if you went through the whole configuration panel where you setup your host name, selected a wallet, etc.

**Comment by Supernaut90** [comment]
okay so ive checked my wallet name, no spaces. wallet key no spaces,  ive also went through the whole configuration a few times and tried a few different distro's of linux so see if that would help. very little success on my end

**Comment by alexsmith540** [comment]
Interesting. Which distro are you using?
We have only tested Ubuntu 20.04 and 21.04

**Comment by Supernaut90** [comment]
Ubuntu 20.04

I tried 21.04 and mint

**Comment by Supernaut90** [comment]
Using /root/.HandyHost/aktData/kubespray/ansible.cfg as config file
[WARNING]: Skipping 'calico_rr' as this is not a valid group definition
[WARNING]:  * Failed to parse
/root/.HandyHost/aktData/kubespray/inventory/handyhost/myinventory.yaml with
auto plugin: no root 'plugin' key found,
'/root/.HandyHost/aktData/kubespray/inventory/handyhost/myinventory.yaml' is
not a valid YAML inventory plugin config file
[WARNING]:  * Failed to parse
/root/.HandyHost/aktData/kubespray/inventory/handyhost/myinventory.yaml with
yaml plugin: calico_rr is not a known host nor group
[WARNING]:  * Failed to parse
/root/.HandyHost/aktData/kubespray/inventory/handyhost/myinventory.yaml with
ini plugin: Invalid host pattern 'all:' supplied, ending in ':' is not allowed,
this character is reserved to provide a port.
[WARNING]: Unable to parse
/root/.HandyHost/aktData/kubespray/inventory/handyhost/myinventory.yaml as an
inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available

PLAY [localhost] ***************************************************************
Wednesday 20 October 2021  21:56:49 -0500 (0:00:00.012)       0:00:00.012 ***** 

TASK [Check 2.9.0 <= Ansible version < 2.11.0] *********************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}
Wednesday 20 October 2021  21:56:49 -0500 (0:00:00.010)       0:00:00.023 ***** 

TASK [Check Ansible version > 2.10.11 when using ansible 2.10] *****************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}
Wednesday 20 October 2021  21:56:49 -0500 (0:00:00.010)       0:00:00.033 ***** 

TASK [Check that python netaddr is installed] **********************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}
Wednesday 20 October 2021  21:56:49 -0500 (0:00:00.015)       0:00:00.048 ***** 

TASK [Check that jinja is not too old (install via pip)] ***********************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}
[WARNING]: Could not match supplied host pattern, ignoring: kube-master

PLAY [Add kube-master nodes to kube_control_plane] *****************************
skipping: no hosts matched
[WARNING]: Could not match supplied host pattern, ignoring: kube-node

PLAY [Add kube-node nodes to kube_node] ****************************************
skipping: no hosts matched
[WARNING]: Could not match supplied host pattern, ignoring: k8s-cluster

PLAY [Add k8s-cluster nodes to k8s_cluster] ************************************
skipping: no hosts matched
[WARNING]: Could not match supplied host pattern, ignoring: calico-rr

PLAY [Add calico-rr nodes to calico_rr] ****************************************
skipping: no hosts matched

PLAY [Add no-floating nodes to no_floating] ************************************
skipping: no hosts matched
[WARNING]: Could not match supplied host pattern, ignoring: no-floating
[WARNING]: Could not match supplied host pattern, ignoring: bastion

PLAY [bastion[0]] **************************************************************
skipping: no hosts matched
[WARNING]: Could not match supplied host pattern, ignoring: calico_rr

PLAY [Gather facts] ************************************************************
Wednesday 20 October 2021  21:56:49 -0500 (0:00:00.016)       0:00:00.065 ***** 
[WARNING]: Unhandled error in Python interpreter discovery for host akash-
genial-natural-country: Failed to connect to the host via ssh: ssh: Could not
resolve hostname akash-genial-natural-country.local: Name or service not known
[WARNING]: Unhandled error in Python interpreter discovery for host akash-
permissible-disgusted-building: Failed to connect to the host via ssh: ssh:
Could not resolve hostname akash-permissible-disgusted-building.local: Name or
service not known
[WARNING]: Unhandled error in Python interpreter discovery for host akash-
doubtful-lavish-pan: Failed to connect to the host via ssh: ssh: Could not
resolve hostname akash-doubtful-lavish-pan.local: Name or service not known

TASK [Gather minimal facts] ****************************************************
fatal: [akash-doubtful-lavish-pan]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"akash-doubtful-lavish-pan.local\". Make sure this host can be reached over ssh: ssh: Could not resolve hostname akash-doubtful-lavish-pan.local: Name or service not known\r\n", "unreachable": true}
fatal: [akash-genial-natural-country]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"akash-genial-natural-country.local\". Make sure this host can be reached over ssh: ssh: Could not resolve hostname akash-genial-natural-country.local: Name or service not known\r\n", "unreachable": true}
fatal: [akash-permissible-disgusted-building]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"akash-permissible-disgusted-building.local\". Make sure this host can be reached over ssh: ssh: Could not resolve hostname akash-permissible-disgusted-building.local: Name or service not known\r\n", "unreachable": true}

PLAY RECAP *********************************************************************
akash-doubtful-lavish-pan  : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
akash-genial-natural-country : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
akash-permissible-disgusted-building : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
localhost                  : ok=4    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

Wednesday 20 October 2021  21:56:59 -0500 (0:00:10.229)       0:00:10.295 ***** 
=============================================================================== 
Gather minimal facts --------------------------------------------------- 10.23s
Check that jinja is not too old (install via pip) ----------------------- 0.02s
Check that python netaddr is installed ---------------------------------- 0.02s
Check Ansible version > 2.10.11 when using ansible 2.10 ----------------- 0.01s
Check 2.9.0 <= Ansible version < 2.11.0 --------------------------------- 0.01s
========= teardown is finished ==========Using /root/.HandyHost/aktData/kubespray/ansible.cfg as config file
[WARNING]: Skipping 'calico_rr' as this is not a valid group definition
[WARNING]:  * Failed to parse
/root/.HandyHost/aktData/kubespray/inventory/handyhost/myinventory.yaml with
auto plugin: no root 'plugin' key found,
'/root/.HandyHost/aktData/kubespray/inventory/handyhost/myinventory.yaml' is
not a valid YAML inventory plugin config file
[WARNING]:  * Failed to parse
/root/.HandyHost/aktData/kubespray/inventory/handyhost/myinventory.yaml with
yaml plugin: calico_rr is not a known host nor group
[WARNING]:  * Failed to parse
/root/.HandyHost/aktData/kubespray/inventory/handyhost/myinventory.yaml with
ini plugin: Invalid host pattern 'all:' supplied, ending in ':' is not allowed,
this character is reserved to provide a port.
[WARNING]: Unable to parse
/root/.HandyHost/aktData/kubespray/inventory/handyhost/myinventory.yaml as an
inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available

PLAY [localhost] ***************************************************************
Wednesday 20 October 2021  21:57:00 -0500 (0:00:00.011)       0:00:00.011 ***** 

TASK [Check 2.9.0 <= Ansible version < 2.11.0] *********************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}
Wednesday 20 October 2021  21:57:00 -0500 (0:00:00.010)       0:00:00.022 ***** 

TASK [Check Ansible version > 2.10.11 when using ansible 2.10] *****************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}
Wednesday 20 October 2021  21:57:00 -0500 (0:00:00.011)       0:00:00.033 ***** 

TASK [Check that python netaddr is installed] **********************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}
Wednesday 20 October 2021  21:57:00 -0500 (0:00:00.017)       0:00:00.051 ***** 

TASK [Check that jinja is not too old (install via pip)] ***********************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}
[WARNING]: Could not match supplied host pattern, ignoring: kube-master

PLAY [Add kube-master nodes to kube_control_plane] *****************************
skipping: no hosts matched
[WARNING]: Could not match supplied host pattern, ignoring: kube-node

PLAY [Add kube-node nodes to kube_node] ****************************************
skipping: no hosts matched
[WARNING]: Could not match supplied host pattern, ignoring: k8s-cluster

PLAY [Add k8s-cluster nodes to k8s_cluster] ************************************
skipping: no hosts matched
[WARNING]: Could not match supplied host pattern, ignoring: calico-rr

PLAY [Add calico-rr nodes to calico_rr] ****************************************
skipping: no hosts matched
[WARNING]: Could not match supplied host pattern, ignoring: no-floating

PLAY [Add no-floating nodes to no_floating] ************************************
skipping: no hosts matched
[WARNING]: Could not match supplied host pattern, ignoring: bastion

PLAY [bastion[0]] **************************************************************
skipping: no hosts matched

PLAY [k8s_cluster:etcd] ********************************************************
Wednesday 20 October 2021  21:57:00 -0500 (0:00:00.022)       0:00:00.074 ***** 
Wednesday 20 October 2021  21:57:00 -0500 (0:00:00.017)       0:00:00.091 ***** 
Wednesday 20 October 2021  21:57:00 -0500 (0:00:00.017)       0:00:00.108 ***** 
Wednesday 20 October 2021  21:57:00 -0500 (0:00:00.015)       0:00:00.124 ***** 
Wednesday 20 October 2021  21:57:00 -0500 (0:00:00.015)       0:00:00.139 ***** 
Wednesday 20 October 2021  21:57:00 -0500 (0:00:00.017)       0:00:00.157 ***** 
Wednesday 20 October 2021  21:57:00 -0500 (0:00:00.010)       0:00:00.167 ***** 
Wednesday 20 October 2021  21:57:00 -0500 (0:00:00.009)       0:00:00.177 ***** 
Wednesday 20 October 2021  21:57:00 -0500 (0:00:00.015)       0:00:00.192 ***** 
Wednesday 20 October 2021  21:57:00 -0500 (0:00:00.014)       0:00:00.207 ***** 
Wednesday 20 October 2021  21:57:00 -0500 (0:00:00.015)       0:00:00.223 ***** 
Wednesday 20 October 2021  21:57:00 -0500 (0:00:00.017)       0:00:00.240 ***** 
Wednesday 20 October 2021  21:57:00 -0500 (0:00:00.009)       0:00:00.250 ***** 
Wednesday 20 October 2021  21:57:00 -0500 (0:00:00.016)       0:00:00.266 ***** 
Wednesday 20 October 2021  21:57:00 -0500 (0:00:00.016)       0:00:00.283 ***** 
Wednesday 20 October 2021  21:57:00 -0500 (0:00:00.015)       0:00:00.298 ***** 
Wednesday 20 October 2021  21:57:00 -0500 (0:00:00.016)       0:00:00.314 ***** 
Wednesday 20 October 2021  21:57:00 -0500 (0:00:00.024)       0:00:00.339 ***** 

TASK [kubespray-defaults : Configure defaults] *********************************
ok: [akash-doubtful-lavish-pan] => {
    "msg": "Check roles/kubespray-defaults/defaults/main.yml"
}
ok: [akash-permissible-disgusted-building] => {
    "msg": "Check roles/kubespray-defaults/defaults/main.yml"
}
ok: [akash-genial-natural-country] => {
    "msg": "Check roles/kubespray-defaults/defaults/main.yml"
}
Wednesday 20 October 2021  21:57:00 -0500 (0:00:00.019)       0:00:00.358 ***** 
Wednesday 20 October 2021  21:57:00 -0500 (0:00:00.024)       0:00:00.382 ***** 
Wednesday 20 October 2021  21:57:00 -0500 (0:00:00.008)       0:00:00.391 ***** 
Wednesday 20 October 2021  21:57:00 -0500 (0:00:00.017)       0:00:00.408 ***** 
Wednesday 20 October 2021  21:57:00 -0500 (0:00:00.009)       0:00:00.418 ***** 
Wednesday 20 October 2021  21:57:00 -0500 (0:00:00.016)       0:00:00.434 ***** 
[WARNING]: raw module does not support the environment keyword
[WARNING]: raw module does not support the environment keyword
[WARNING]: raw module does not support the environment keyword

TASK [bootstrap-os : Fetch /etc/os-release] ************************************
fatal: [akash-permissible-disgusted-building]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname akash-permissible-disgusted-building.local: Name or service not known", "unreachable": true}
fatal: [akash-genial-natural-country]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname akash-genial-natural-country.local: Name or service not known", "unreachable": true}
fatal: [akash-doubtful-lavish-pan]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname akash-doubtful-lavish-pan.local: Name or service not known", "unreachable": true}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
akash-doubtful-lavish-pan  : ok=1    changed=0    unreachable=1    failed=0    skipped=22   rescued=0    ignored=0   
akash-genial-natural-country : ok=1    changed=0    unreachable=1    failed=0    skipped=16   rescued=0    ignored=0   
akash-permissible-disgusted-building : ok=1    changed=0    unreachable=1    failed=0    skipped=16   rescued=0    ignored=0   
localhost                  : ok=4    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

Wednesday 20 October 2021  21:57:05 -0500 (0:00:05.045)       0:00:05.480 ***** 
=============================================================================== 
bootstrap-os : Fetch /etc/os-release ------------------------------------ 5.05s
download : download | Download files / images --------------------------- 0.02s
kubespray-defaults : Gather ansible_default_ipv4 from all hosts --------- 0.02s
Check that jinja is not too old (install via pip) ----------------------- 0.02s
kubespray-defaults : Configure defaults --------------------------------- 0.02s
kubespray-defaults : set fallback_ips ----------------------------------- 0.02s
download : prep_download | Set image pull/info command for containerd and crio on localhost --- 0.02s
Check that python netaddr is installed ---------------------------------- 0.02s
download : prep_download | Create staging directory on remote node ------ 0.02s
download : prep_download | Set a few facts ------------------------------ 0.02s
download : prep_download | Set image pull/info command for docker ------- 0.02s
container-engine/crictl : install crictĺ -------------------------------- 0.02s
kubespray-defaults : Populates no_proxy to all hosts -------------------- 0.02s
container-engine/nerdctl : nerdctl | Download nerdctl ------------------- 0.02s
download : download | Get kubeadm binary and list of required images ---- 0.02s
download : prep_download | Set image pull/info command for docker on localhost --- 0.02s
download : prep_download | Set image pull/info command for containerd and crio --- 0.02s
download : prep_download | Register docker images info ------------------ 0.02s
container-engine/nerdctl : nerdctl | Copy nerdctl binary from download dir --- 0.02s
download : prep_download | Parse the outputs of the previous commands --- 0.02s
POST INSTALL: checkout akash repo
POST INSTALL: Fetching origin
POST INSTALL: HEAD is now at fcfed2dc docs(provider): Update with info from the community
POST INSTALL: done checking out akash repo
POST INSTALL: INGRESS NODE NAME akash-doubtful-lavish-pan
MASTER IP 192.168.0.27
POST INSTALL: Warning: Identity file /root/.ssh/handyhost not accessible: No such file or directory.
POST INSTALL: ssh: connect to host 192.168.0.27 port 22: No route to host

POST INSTALL: W1020 21:57:09.336984   37634 loader.go:221] Config not found: /root/.HandyHost/aktData/admin.conf
POST INSTALL: The connection to the server localhost:8080 was refused - did you specify the right host or port?
POST INSTALL: W1020 21:57:09.354856   37660 loader.go:221] Config not found: /root/.HandyHost/aktData/admin.conf
POST INSTALL: The connection to the server localhost:8080 was refused - did you specify the right host or port?
POST INSTALL: W1020 21:57:09.371700   37684 loader.go:221] Config not found: /root/.HandyHost/aktData/admin.conf
POST INSTALL: The connection to the server localhost:8080 was refused - did you specify the right host or port?
POST INSTALL: W1020 21:57:09.388208   37703 loader.go:221] Config not found: /root/.HandyHost/aktData/admin.conf
POST INSTALL: The connection to the server localhost:8080 was refused - did you specify the right host or port?
POST INSTALL: W1020 21:57:09.404676   37725 loader.go:221] Config not found: /root/.HandyHost/aktData/admin.conf
POST INSTALL: The connection to the server localhost:8080 was refused - did you specify the right host or port?
POST INSTALL: W1020 21:57:09.421740   37749 loader.go:221] Config not found: /root/.HandyHost/aktData/admin.conf
POST INSTALL: The connection to the server localhost:8080 was refused - did you specify the right host or port?
POST INSTALL: ./postInitK8sCluster.sh: line 50: cd: ../_docs: No such file or directory
POST INSTALL: W1020 21:57:09.439024   37771 loader.go:221] Config not found: /root/.HandyHost/aktData/admin.conf
POST INSTALL: The connection to the server localhost:8080 was refused - did you specify the right host or port?
POST INSTALL: Error: evalsymlink failure on './kustomize/akash-services/' : lstat /root/.HandyHost/aktData/kustomize: no such file or directory
POST INSTALL: W1020 21:57:09.457932   37797 loader.go:221] Config not found: /root/.HandyHost/aktData/admin.conf
POST INSTALL: The connection to the server localhost:8080 was refused - did you specify the right host or port?
POST INSTALL: W1020 21:57:09.477364   37844 loader.go:221] Config not found: /root/.HandyHost/aktData/admin.conf
POST INSTALL: The connection to the server localhost:8080 was refused - did you specify the right host or port?
Setting up Metrics ServerPOST INSTALL: W1020 21:57:10.485110   37895 loader.go:221] Config not found: /root/.HandyHost/aktData/admin.conf
POST INSTALL: The connection to the server localhost:8080 was refused - did you specify the right host or port?
========= init is finished ==========

**Comment by alexsmith540** [comment]
Ok thinking about it I believe I know why it can’t ssh into the nodes. You mentioned that you tried a few different linux distros. So when you initially built your thumb drive and flashed the nodes, were you on a former distro/no longer the current Linux on the HandyHost node? 
If the above statement is true: it would make sense you couldn’t ssh into the nodes any longer as ssh is permissioned by an ssh key file generated when you built the thumbdrive, not by password. And the ssh key wouldnt be on the new distro anymore. 
So if this is the case here’s how to solve.
1. Burn a new thumb drive from the HandyHost node
2. Uncheck your akash nodes in your config, save config, then refresh the browser window. The nodes list should now be empty.
3. Power off the akash nodes, then flash them with the thumb drive one at a time until they’re all setup.
4. Now fetch nodes and add them to your config and save config.
5. Click Build kubernetes cluster. 
6. If the cluster build seemed to work, evidenced by a bunch of success messages at the last part of the logs, then update your port forwarding in your router to the new ingress node IP
7. Should be good to go.
