### ISSUE TITLE
How do I check my configuration

### ISSUE THREAD

**Issue by avolon42x** [HandyOSS/HandyHost#12]
I’m unsure if my configuration is properly set up.
I see that two bids are closed. But in provider logs I get some errors where I’m unsure if my setup is proper:
`
E[2021-10-20|14:06:47.685] **error requesting account cmp=client/broadcaster err="post failed: Post \"http://135.181.181.121:28957\": EOF"**
I[2021-10-20|14:06:57.715] syncing sequence cmp=client/broadcaster local=54 remote=54
D[2021-10-20|14:07:01.188] inventory fetched module=provider-cluster cmp=service cmp=inventory-service nodes=3
..
..
I[2021-10-20|14:07:21.182] order detected module=bidengine-service order=order/akash1fyghadlr9gd24f4uy8380uf7sp8qkuscgzaz76/3140397/1/1
I[2021-10-20|14:07:21.215] group fetched module=bidengine-order order=akash1fyghadlr9gd24f4uy8380uf7sp8qkuscgzaz76/3140397/1/1
D[2021-10-20|14:07:21.215] **unable to fulfill: incompatible provider attributes** module=bidengine-order order=akash1fyghadlr9gd24f4uy8380uf7sp8qkuscgzaz76/3140397/1/1
D[2021-10-20|14:07:21.215] declined to bid module=bidengine-order order=akash1fyghadlr9gd24f4uy8380uf7sp8qkuscgzaz76/3140397/1/1
I[2021-10-20|14:07:21.215] shutting down module=bidengine-order order=akash1fyghadlr9gd24f4uy8380uf7sp8qkuscgzaz76/3140397/1/1
..
..
I[2021-10-20|14:09:07.715] syncing sequence                             cmp=client/broadcaster local=54 remote=54
I[2021-10-20|14:09:08.064] **balance below target amount, withdrawing now module=provider-service** cmp=balance-checker

Regarding balance I have around 138 AKT in the wallet - enough?

**Comment by avolon42x** [comment]
Another suspicious error:

2021/10/20 14:23:05 http: TLS handshake error from xx.xx.xxx.61:57411: tls: client offered only unsupported versions: [302 301]

-> Took out the IP connecting with x’s.

**Comment by alexsmith540** [comment]
Also that tls handshake error is likely fine, I’m guessing you’re running dvpn too? In dvpn we use self signed certificates so that’s likely why you see it.
