### ISSUE TITLE
Custom Sia Blockchain/Wallet path.

### ISSUE THREAD

**Issue by Roalkege** [HandyOSS/HandyHost#13]
How can I customize the path for the Sia Blockchain to use a specific disk?

**Comment by alexsmith540** [comment]
Currently it's not a config parameter but I can totally see why you would want this and will add this to our next release. 
In the interim, one thing you could try (if you like the command line anyway) :
1. after running sia once from HandyHost, you can stop sia in your terminal by running: ```~/go/bin/siac -a localhost:10801 stop```. Note that if you installed on ubuntu you will probably need to run this in a root session with ```sudo su```. 
2. Once sia is stopped you can move the folder ```~/.HandyHost/siaData``` to whatever partition or disk you'd like to. 
3. symlink the new siaData location back to ```~/.HandyHost/siaData``` like: ```ln -s /my/new/path ~/.HandyHost/siaData```
4. Then restart handyhost application and you should be good to go.

**Comment by Roalkege** [comment]
Thank you, that works.
