### ISSUE TITLE
Accept 12 words mnemonic from keplr wallet

### ISSUE THREAD

**Issue by henaff** [HandyOSS/HandyHost#14]
Hi, i see you must enter a 24 words mnemonic to recover a wallet for a Sentinel node. So it's not possible to use an existing Cosmos wallet as from Keplr. From docker i can use the 12 words mnemonic.
Sorry in advance maybe i don't understand the cosmos network.

**Comment by alexsmith540** [comment]
Thanks for the tip. I have only ever had 24 word mnemonics using the wallet directly so I totally missed this. I'll add support for 12 word mnemonics in our next update. Thanks for the heads up!

**Comment by Kdenery** [comment]
Can we get this update implemented in the mobile app as well?

**Comment by alexsmith540** [comment]
I just released 12-word mnemonic support in v0.5.1 FYI
