### ISSUE TITLE
unable to fulfill: incompatible provider attributes

### ISSUE THREAD

**Issue by avolon42x** [HandyOSS/HandyHost#15]
I'm always getting this message in the provider logs. how can I get more information about that error? Tried several deployments with Akashlytics deploy tool.

**Comment by alexsmith540** [comment]
Generally incompatible provider attributes means the signed_by parameter does not matched (aka your provider is not signed_by an entity listed in the deploy.yml). Other times it could be that they want 10 CPUs and you have 5.
