### ISSUE TITLE
Unable to start Handyhost as daemon

### ISSUE THREAD

**Issue by BigCheeseTC** [HandyOSS/HandyHost#16]
After installing and verifying docker is installed, this is the response I receive when trying to start HandyHost daemon. Using Ubuntu 20.04 64-bit.

```
~# sudo systemctl start handyhost
sudo: unable to resolve host dvpn11: Name or service not known
```
This seems to be the reason that I am unable to create a new wallet as the reply is a denial of login of daemon.

This is what I see when trying to create a new wallet:

`Error: Unable to find image 'sentinel-dvpn-node:latest' locally docker: Error response from daemon: pull access denied for sentinel-dvpn-node, repository does not exist or may require 'docker login': denied: requested access to the resource is denied. See 'docker run --help'.`

When listing enabled daemons:

`handyhost.service                          generated       enabled`

When listing running daemons:

` handyhost.service                                                                                loaded active running   LSB: HandyHost`

Any help would be appreciated.

**Comment by BigCheeseTC** [comment]
I was able to get the daemon to run. However, I still can't create a wallet due to previously mentioned error. Here is a log:

`syscall: 'open',
  code: 'ENOENT',
  path: '/root/.sentinelnode/config.toml'
}
(node:31750) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'node' of undefined
    at file:///opt/handyhost/dvpnAPI/Setup.js:240:32
    at Array.map (<anonymous>)
    at file:///opt/handyhost/dvpnAPI/Setup.js:239:32
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:31750) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
hh version data?? { latest: 'v0.4.9', local: 'v0.4.9', isUpToDate: true }
check machine status dvpn
error Error: ENOENT: no such file or directory, open '/root/.sentinelnode/config.toml'
    at Object.openSync (fs.js:476:3)
    at Object.readFileSync (fs.js:377:35)
    at file:///opt/handyhost/dvpnAPI/Setup.js:207:26
    at new Promise (<anonymous>)
    at DVPNSetup.getConfigs (file:///opt/handyhost/dvpnAPI/Setup.js:206:10)
    at file:///opt/handyhost/dvpnAPI/Setup.js:223:9
    at new Promise (<anonymous>)
    at DVPNSetup.getPorts (file:///opt/handyhost/dvpnAPI/Setup.js:222:10)
    at file:///opt/handyhost/dvpnAPI/Setup.js:456:9
    at new Promise (<anonymous>) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/root/.sentinelnode/config.toml'
}
(node:31750) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'node' of undefined
    at file:///opt/handyhost/dvpnAPI/Setup.js:224:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:31750) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
is positional [ 'api', 'dvpn', 'getDashboardStats' ]
is positional [ 'api', 'dvpn', 'getState' ]
is positional [ 'api', 'getIP' ]
HandyHost versionData { latest: 'v0.4.9', local: 'v0.4.9', isUpToDate: true }
is positional [ 'api', 'dvpn', 'initWallet' ]
err [Error: SQLITE_CANTOPEN: unable to open database file] {
  errno: 14,
  code: 'SQLITE_CANTOPEN'
`

**Comment by BigCheeseTC** [comment]
I have no issues with AKT or Sia. Only DVPN is problematic.

**Comment by alexsmith540** [comment]
Interesting, I havent seen this behavior before. To help me replicate/test here can you tell me if you installed via the .deb package or from source?

**Comment by BigCheeseTC** [comment]
Thank you for quick response. I installed from .deb.

**Comment by alexsmith540** [comment]
Seems like handyhost isn't able to find the docker container from the looks of those logs. I just ran thru the installer on a fresh ubuntu 20 but couldnt replicate the error you saw. 
A couple of follow up questions:
1. How did you run the .deb package, on cli like: ```sudo dpkg -i handyhost_v0.5.0.deb || sudo apt install -f -y``` or with something else?
2. As your regular (non root) user can you run: ```docker image ls``` and then run the same command as the root user like ```sudo docker image ls```

**Comment by thepapallot** [comment]
Hi, I am using a raspberry 4 booting from an SDD and have the same problem.
I ahve tried sudo docker image ls and no image appear at all

**Comment by alexsmith540** [comment]
@thepapallot question: did you install the .deb file with the command listed above in item 1, or thru some other tool? I have been trying to replicate this bug but not having any luck yet

**Comment by thepapallot** [comment]
I am using a brand new raspi 4 and also a new sdd card. 
I have installed ubuntu into the sdd using rpi imager. Then connected the sdd to the raspi and boot it up.

After that, connected the ethernet cable and i have installed the .deb file throught the command specified.

**Comment by degen2285** [comment]
I have the same issue as @thepapallot also running a New Raspi 4 and SSD.. Installed Ubuntu 20 through Rasp imager.. and used install command sudo dpkg -i handyhost_v0.5.0.deb || sudo apt install -f -y     

Akash and Sia work fine. Unable to create a DVPN wallet with same error message noted above. I ran the docker image ls command and the sentinel-dvpn-node is not present in the list.

**Comment by alexsmith540** [comment]
@degen2285 and anybody else here on the thread:: So that I can replicate this: 
Are you using ubuntu desktop or server version 20? Also are you using 64-bit?
I have really only tested HandyHost on 64-bit desktop 20.04 (x86, non-raspi) and 64-bit 21.04 desktop (raspi4) so I'd love to know which ubuntu's i need to verify on as 64-bit 21.04 desktop worked fine for me out of the box. I'm about to test 64-bit 21.10 desktop and 20.04 server later tonight too FYI.

**Comment by alexsmith540** [comment]
Ok I was able to replicate this on ubuntu 21.10, it seems that something changed either in the kernel or docker.. 
How to fix:
1. ```sudo apt install linux-modules-extra-raspi``` (this will take like 10 minutes)
2. After that installs, restart your raspi
3. ```sudo rm -rf /root/.HandyHost/sentinelData``` will remove the sentinel-dvpn-node source so that we can attempt to rebuild the docker container.
4. Re-run the installer wherever you downloaded the deb package like: ```sudo dpkg -i handyhost_v0.5.0.deb```
5. You should see in the logs that it will take ~20 minutes to build the docker container this time.
6. After its all finished, open the gui and now you can create/import DVPN wallets.

**Comment by degen2285** [comment]
Thanks @alexsmith540 Wallet created and DVPN host running

**Comment by thepapallot** [comment]
it worked for me as well. Thank a lot @alexsmith540.

**Comment by alexsmith540** [comment]
Awesome, thanks for the heads up and verification. I updated the docs/install docs with this dependency and closing this issue.
