### ISSUE TITLE
Error: Unable to find image 'sentinel-dvpn-node:latest' locally docker:

### ISSUE THREAD

**Issue by alyasboytigas** [HandyOSS/HandyHost#21]
Just installed handyhost on PI 4B running Ubuntu Desktop 21.10 64-bit

Sentinel - When I try creating wallet I get the following error: any idea? thanks

Error: Unable to find image 'sentinel-dvpn-node:latest' locally docker: Error response from daemon: pull access denied for sentinel-dvpn-node, repository does not exist or may require 'docker login': denied: requested access to the resource is denied. See 'docker run --help'.

**Comment by alexsmith540** [comment]
The solution is here:
https://github.com/HandyOSS/HandyHost/issues/16#issuecomment-968204837

**Comment by alyasboytigas** [comment]
thank you thank you it worked.

**Comment by alexsmith540** [comment]
duplicate to #16, closing.
