### ISSUE TITLE
Wallet Balance on Sentinel keeps dropping

### ISSUE THREAD

**Issue by alyasboytigas** [HandyOSS/HandyHost#22]
hello,
Per my messages on twitter my wallet balance keeps dropping. eventhough I change the the time interval to 48hrs. thanks.

**Comment by alexsmith540** [comment]
You might try plugging your wallet address into a block explorer like https://www.mintscan.io/sentinel and see what transactions/fees occur and how often. Also, did you restart your dvpn node after you saved your config with the updated time intervals?

**Comment by alyasboytigas** [comment]
i check on mintscan first latest 5:

2021-11-22 09:29:48
2021-11-22 08:34:50
2021-11-22 07:39:47
2021-11-22 06:44:52
2021-11-22 05:49:52 

Yes restarted dvpn mode.

**Comment by alyasboytigas** [comment]
Just re -install the whole OS ... and re-install handhost... for some reason I change:

Set Sessions Interval 1m0s Time interval between each set_sessions operation; Format: 0h0m0s

Tried 5m - 10m - 20m even 55m

I get error:

Error: invalid section node: interval_set_sessions cannot be greater than 55m0s

What is the default or working set interval session?

Thanks.

**Comment by alexsmith540** [comment]
Seems like the max is ```55m0s``` <<<also needs to be formatted like that ```55m0s```, seems like youre missing the "0s" on the end of those which is probably why you see that error. Also I checked and any of the intervals listed are at their max settings (update sessions = 1h55m0s, update status = 55m0s). 
If you want to try to minimize what you spend on transaction fees you could also try to play with the gas price in the advanced options and see if your transactions complete at a lower gas price.

**Comment by alyasboytigas** [comment]
sorry for misunderstanding yes i have the 0s there right now what i have on set session intervals 55m0s i get:


Error: invalid section node: interval_set_sessions cannot be greater than 10m0s

**Comment by alexsmith540** [comment]
For the set sessions interval operation, the max interval time is 10 minutes: 10m0s

**Comment by alyasboytigas** [comment]
Thank you so much for your help really appreciate it.

As for the gas price I have 0.1udvpn should I go down more?

**Comment by alexsmith540** [comment]
Glad to help.
Yeah you could try 0.05udvpn and monitor the block explorer to see if your transactions are still going through. If so then drop further until you find a sweet spot in price.

**Comment by alyasboytigas** [comment]
got it thank you thank you.

**Comment by alexsmith540** [comment]
👍
