### ISSUE TITLE
Siacoin. Synced undefined/349999

### ISSUE THREAD

**Issue by Supernaut90** [HandyOSS/HandyHost#23]
Woke up to check the siacoin rig, it seems it's offline and can't connect? Can't find much information other then that. 

Tried a reboot etc. Need some direction on troubleshooting/ fixing

"Synced : undefined/339854"

Thank you

**Comment by alexsmith540** [comment]
Did you start the chain syncing previously/create a wallet/etc when you started up the sia UI? 
If you hadnt yet created a wallet you might try creating one and see if that jump starts the service or unlocks some of the sia API's. Alternately you could check the sia logs in /root/.HandyHost/siaData/siad-output.log and see if it yields any errors on the sia side. 
And if you really want to I can show you how to just remove the sia data directory altogether which just forces sia to start over on the sync.

**Comment by Supernaut90** [comment]
Will deleting the data directory cause me to lose any of my contracts?  I had 64 active contracts and I don't want to miss out on those

**Comment by alexsmith540** [comment]
Yeah in that case no definitely dont delete the data dir. Since you have been synced before it likely means something with sia not starting up properly, can you see what your sia logs in /root/.HandyHost/siaData/siad-output.log contain?

**Comment by Supernaut90** [comment]
> Wallet: scanned to height 336925...
> Wallet: scanned to height 337176...
> Wallet: scanned to height 337402...
> Wallet: scanned to height 337677...
> Wallet: scanned to height 337956...
> Wallet: scanned to height 338196...
> Wallet: scanned to height 338436...
> Wallet: scanned to height 338670...
> Wallet: scanned to height 338905...
> Done!
> 
> Caught stop signal, quitting...
> Closing accounting...
> Closing renter...
> Closing host...
> Closing wallet...
> Closing transactionpool...
> Closing consensusset...
> Closing gateway...
> Closing siamux...
> Shutdown complete.
> siad v1.5.7
> Git Revision ✗-a4736ae74
> Loading...
> (1/8) Loading siad...
> (2/8) Loading gateway...
> (3/8) Loading consensus...
> (4/8) Loading transaction pool...
> (5/8) Loading wallet...
> (6/8) Loading host...
> (7/8) Loading renter...
> (8/8) Loading accounting...
> API is now available, synchronous startup completed in 10.494 seconds
> Finished full setup in 6m22s
> 
> Caught stop signal, quitting...
> Closing accounting...
> Closing renter...
> Closing host...
> Closing wallet...
> Closing transactionpool...
> Closing consensusset...
> Closing gateway...
> Closing siamux...
> Shutdown complete.
> siad v1.5.7
> Git Revision ✗-a4736ae74
> Loading...
> (1/8) Loading siad...
> (2/8) Loading gateway...
> (3/8) Loading consensus...
> (4/8) Loading transaction pool...
> (5/8) Loading wallet...
> (6/8) Loading host...
> (7/8) Loading renter...
> (8/8) Loading accounting...
> API is now available, synchronous startup completed in 12.137 seconds
> Finished full setup in 6m42s
> 
> Caught stop signal, quitting...
> Closing accounting...
> Closing renter...
> siad v1.5.7
> Git Revision ✗-a4736ae74
> Loading...
> (1/8) Loading siad...
> (2/8) Loading gateway...
> (3/8) Loading consensus...
> (4/8) Loading transaction pool...
> (5/8) Loading wallet...
> (6/8) Loading host...
> (7/8) Loading renter...
> (8/8) Loading accounting...
> API is now available, synchronous startup completed in 12.325 seconds
> Finished full setup in 45s
> 
> Caught stop signal, quitting...
> Closing accounting...
> Closing renter...
> Closing host...
> Closing wallet...
> Closing transactionpool...
> Closing consensusset...
> Closing gateway...
> Closing siamux...
> Shutdown complete.
> siad v1.5.7
> Git Revision ✗-a4736ae74
> Loading...
> (1/8) Loading siad...
> (2/8) Loading gateway...
> (3/8) Loading consensus...
> (4/8) Loading transaction pool...
> (5/8) Loading wallet...
> (6/8) Loading host...
> (7/8) Loading renter...
> (8/8) Loading accounting...
> API is now available, synchronous startup completed in 12.005 seconds
> Finished full setup in 2m3s
> 
> Caught stop signal, quitting...
> Closing accounting...
> Closing renter...
> Closing host...
> Closing wallet...
> Closing transactionpool...
> Closing consensusset...
> Closing gateway...
> Closing siamux...
> Shutdown complete.
> siad v1.5.7
> Git Revision ✗-a4736ae74
> Loading...
> (1/8) Loading siad...
> (2/8) Loading gateway...
> (3/8) Loading consensus...
> (4/8) Loading transaction pool...
> (5/8) Loading wallet...
> (6/8) Loading host...
> (7/8) Loading renter...
> (8/8) Loading accounting...
> API is now available, synchronous startup completed in 12.254 seconds
> Finished full setup in 39s
> 
> Caught stop signal, quitting...
> Closing accounting...
> Closing renter...
> Closing host...
> Closing wallet...
> Closing transactionpool...
> Closing consensusset...
> Closing gateway...
> Closing siamux...
> Shutdown complete.
> siad v1.5.7
> Git Revision ✗-a4736ae74
> Loading...
> (1/8) Loading siad...
> (2/8) Loading gateway...
> (3/8) Loading consensus...
> (4/8) Loading transaction pool...
> (5/8) Loading wallet...
> (6/8) Loading host...
> (7/8) Loading renter...
> (8/8) Loading accounting...
> API is now available, synchronous startup completed in 12.297 seconds
> Finished full setup in 40s
> 
> Caught stop signal, quitting...
> Closing accounting...
> Closing renter...
> Closing host...
> Closing wallet...
> Closing transactionpool...
> Closing consensusset...
> Closing gateway...
> Closing siamux...
> Shutdown complete.
> siad v1.5.7
> Git Revision ✗-a4736ae74
> Loading...
> (1/8) Loading siad...
> (2/8) Loading gateway...
> (3/8) Loading consensus...
> (4/8) Loading transaction pool...
> (5/8) Loading wallet...
> (6/8) Loading host...
> (7/8) Loading renter...
> (8/8) Loading accounting...
> API is now available, synchronous startup completed in 12.567 seconds
> Finished full setup in 40s
> 
> Caught stop signal, quitting...
> Closing accounting...
> Closing renter...
> Closing host...
> Closing wallet...
> Closing transactionpool...
> Closing consensusset...
> Closing gateway...
> Closing siamux...
> Shutdown complete.
> siad v1.5.7
> Git Revision ✗-a4736ae74
> Loading...
> (1/8) Loading siad...
> (2/8) Loading gateway...
> (3/8) Loading consensus...
> (4/8) Loading transaction pool...
> (5/8) Loading wallet...
> (6/8) Loading host...
> (7/8) Loading renter...
> (8/8) Loading accounting...
> API is now available, synchronous startup completed in 14.089 seconds
> Finished full setup in 39s
> 
> Caught stop signal, quitting...
> Closing accounting...
> Closing renter...
> Closing host...
> Closing wallet...
> Closing transactionpool...
> Closing consensusset...
> Closing gateway...
> Closing siamux...
> Shutdown complete.
> siad v1.5.7
> Git Revision ✗-a4736ae74
> Loading...
> (1/8) Loading siad...
> (2/8) Loading gateway...
> (3/8) Loading consensus...
> (4/8) Loading transaction pool...
> (5/8) Loading wallet...
> (6/8) Loading host...
> (7/8) Loading renter...
> (8/8) Loading accounting...
> API is now available, synchronous startup completed in 13.402 seconds
> Finished full setup in 36s
> 
> Caught stop signal, quitting...
> Closing accounting...
> Closing renter...
> Closing host...
> Closing wallet...
> Closing transactionpool...
> Closing consensusset...
> Closing gateway...
> Closing siamux...
> Shutdown complete.
> siad v1.5.7
> Git Revision ✗-a4736ae74
> Loading...
> (1/8) Loading siad...
> (2/8) Loading gateway...
> (3/8) Loading consensus...
> (4/8) Loading transaction pool...
> (5/8) Loading wallet...
> (6/8) Loading host...
> (7/8) Loading renter...
> (8/8) Loading accounting...
> API is now available, synchronous startup completed in 12.127 seconds
> Finished full setup in 34s
> 
> Caught stop signal, quitting...
> Closing accounting...
> Closing renter...
> Closing host...
> Closing wallet...
> Closing transactionpool...
> Closing consensusset...
> Closing gateway...
> Closing siamux...
> Shutdown complete.
> siad v1.5.7
> Git Revision ✗-a4736ae74
> Loading...
> (1/8) Loading siad...
> (2/8) Loading gateway...
> (3/8) Loading consensus...
> (4/8) Loading transaction pool...
> (5/8) Loading wallet...
> (6/8) Loading host...
> (7/8) Loading renter...
> (8/8) Loading accounting...
> API is now available, synchronous startup completed in 14.104 seconds
> Finished full setup in 35s
> 
> Caught stop signal, quitting...
> Closing accounting...
> Closing renter...
> Closing host...
> siad v1.5.7
> Git Revision ✗-a4736ae74
> Loading...
> (1/8) Loading siad...
> (2/8) Loading gateway...
> (3/8) Loading consensus...
> (4/8) Loading transaction pool...
> (5/8) Loading wallet...
> (6/8) Loading host...
> (7/8) Loading renter...
> ERROR: [server is unable to create the Sia node; unable to create renter; unable to read persisted json object from disk: loading a file with a bad checksum]
> [server is unable to create the Sia node; unable to create renter; unable to read persisted json object from disk: loading a file with a bad checksum]
> siad v1.5.7
> Git Revision ✗-a4736ae74
> Loading...
> (1/8) Loading siad...
> (2/8) Loading gateway...
> (3/8) Loading consensus...
> (4/8) Loading transaction pool...
> (5/8) Loading wallet...
> (6/8) Loading host...
> (7/8) Loading renter...
> (8/8) Loading accounting...
> API is now available, synchronous startup completed in 24.641 seconds
> Finished full setup in 52s
> panic: runtime error: index out of range [844428784177152] with length 281474976710655
> 
> goroutine 1567581 [running]:
> gitlab.com/NebulousLabs/bolt.(*DB).page(...)
> 	/root/go/pkg/mod/gitlab.com/!nebulous!labs/bolt@v1.4.4/db.go:891
> gitlab.com/NebulousLabs/bolt.(*Tx).page(...)
> 	/root/go/pkg/mod/gitlab.com/!nebulous!labs/bolt@v1.4.4/tx.go:618
> gitlab.com/NebulousLabs/bolt.(*node).spill(0xc003343490, 0xc00046a378, 0x1)
> 	/root/go/pkg/mod/gitlab.com/!nebulous!labs/bolt@v1.4.4/node.go:359 +0x6f5
> gitlab.com/NebulousLabs/bolt.(*node).spill(0xc003343420, 0x0, 0x0)
> 	/root/go/pkg/mod/gitlab.com/!nebulous!labs/bolt@v1.4.4/node.go:346 +0xba
> gitlab.com/NebulousLabs/bolt.(*node).spill(0xc0027faee0, 0x0, 0x0)
> 	/root/go/pkg/mod/gitlab.com/!nebulous!labs/bolt@v1.4.4/node.go:346 +0xba
> gitlab.com/NebulousLabs/bolt.(*node).spill(0xc001322a10, 0xc0033fa210, 0xc005a394e8)
> 	/root/go/pkg/mod/gitlab.com/!nebulous!labs/bolt@v1.4.4/node.go:346 +0xba
> gitlab.com/NebulousLabs/bolt.(*Bucket).spill(0xc008fc7e80, 0xc005a39500, 0xb)
> 	/root/go/pkg/mod/gitlab.com/!nebulous!labs/bolt@v1.4.4/bucket.go:570 +0x49a
> gitlab.com/NebulousLabs/bolt.(*Bucket).spill(0xc00cd2cc58, 0x94af8035cbf, 0x14b17e0)
> 	/root/go/pkg/mod/gitlab.com/!nebulous!labs/bolt@v1.4.4/bucket.go:537 +0x3f6
> gitlab.com/NebulousLabs/bolt.(*Tx).Commit(0xc00cd2cc40, 0x0, 0x0)
> 	/root/go/pkg/mod/gitlab.com/!nebulous!labs/bolt@v1.4.4/tx.go:160 +0xe8
> gitlab.com/NebulousLabs/bolt.(*DB).Update(0xc000154800, 0xc009a05a48, 0x0, 0x0)
> 	/root/go/pkg/mod/gitlab.com/!nebulous!labs/bolt@v1.4.4/db.go:706 +0x105
> go.sia.tech/siad/modules/consensus.(*ConsensusSet).managedAcceptBlocks(0xc00018eb00, 0xc009a05c30, 0x1, 0x1, 0x1e8400, 0x0, 0x0)
> 	/root/.HandyHost/siaRepo/modules/consensus/accept.go:247 +0x44b
> go.sia.tech/siad/modules/consensus.(*ConsensusSet).managedReceiveBlock.func1(0xf97418, 0xc0039259c0, 0x14b17e0, 0x0)
> 	/root/.HandyHost/siaRepo/modules/consensus/synchronize.go:529 +0x206
> go.sia.tech/siad/modules/gateway.(*Gateway).managedRPC(0xc00018c6c0, 0xc00012db60, 0x12, 0xe1a369, 0x7, 0xc006a59bc0, 0x0, 0x0)
> 	/root/.HandyHost/siaRepo/modules/gateway/rpc.go:70 +0x30e
> go.sia.tech/siad/modules/gateway.(*Gateway).RPC(0xc00018c6c0, 0xc00012db60, 0x12, 0xe1a369, 0x7, 0xc006a59bc0, 0x0, 0x0)
> 	/root/.HandyHost/siaRepo/modules/gateway/rpc.go:83 +0xe8
> go.sia.tech/siad/modules/consensus.(*ConsensusSet).threadedRPCRelayHeader.func5(0xc0049030b0, 0xc00018eb00, 0xf97418, 0xc00401f260, 0xc0090df5e0, 0xc00530ec40)
> 	/root/.HandyHost/siaRepo/modules/consensus/synchronize.go:459 +0x1b9
> created by go.sia.tech/siad/modules/consensus.(*ConsensusSet).threadedRPCRelayHeader
> 	/root/.HandyHost/siaRepo/modules/consensus/synchronize.go:457 +0x489
> siad v1.5.7
> Git Revision ✗-a4736ae74
> Loading...
> (1/8) Loading siad...
> (2/8) Loading gateway...
> (3/8) Loading consensus...
> (4/8) Loading transaction pool...
> (5/8) Loading wallet...
> (6/8) Loading host...
> (7/8) Loading renter...
> ERROR: [server is unable to create the Sia node; unable to create renter; unable to read persisted json object from disk: loading a file with a bad checksum]
> [server is unable to create the Sia node; unable to create renter; unable to read persisted json object from disk: loading a file with a bad checksum]
> siad v1.5.7
> Git Revision ✗-a4736ae74
> Loading...
> (1/8) Loading siad...
> (2/8) Loading gateway...
> (3/8) Loading consensus...
> (4/8) Loading transaction pool...
> (5/8) Loading wallet...
> (6/8) Loading host...
> (7/8) Loading renter...
> ERROR: [server is unable to create the Sia node; unable to create renter; unable to read persisted json object from disk: loading a file with a bad checksum]
> [server is unable to create the Sia node; unable to create renter; unable to read persisted json object from disk: loading a file with a bad checksum]
> siad v1.5.7
> Git Revision ✗-a4736ae74
> Loading...
> (1/8) Loading siad...
> (2/8) Loading gateway...
> (3/8) Loading consensus...
> (4/8) Loading transaction pool...
> (5/8) Loading wallet...
> (6/8) Loading host...
> (7/8) Loading renter...
> ERROR: [server is unable to create the Sia node; unable to create renter; unable to read persisted json object from disk: loading a file with a bad checksum]
> [server is unable to create the Sia node; unable to create renter; unable to read persisted json object from disk: loading a file with a bad checksum]
> siad v1.5.7
> Git Revision ✗-a4736ae74
> Loading...
> (1/8) Loading siad...
> (2/8) Loading gateway...
> (3/8) Loading consensus...
> (4/8) Loading transaction pool...
> (5/8) Loading wallet...
> (6/8) Loading host...
> (7/8) Loading renter...
> ERROR: [server is unable to create the Sia node; unable to create renter; unable to read persisted json object from disk: loading a file with a bad checksum]
> [server is unable to create the Sia node; unable to create renter; unable to read persisted json object from disk: loading a file with a bad checksum]
> siad v1.5.7
> Git Revision ✗-031dcde1f
> Loading...
> (1/8) Loading siad...
> (2/8) Loading gateway...
> (3/8) Loading consensus...
> (4/8) Loading transaction pool...
> (5/8) Loading wallet...
> (6/8) Loading host...
> (7/8) Loading renter...
> ERROR: [server is unable to create the Sia node; unable to create renter; unable to read persisted json object from disk: loading a file with a bad checksum]
> [server is unable to create the Sia node; unable to create renter; unable to read persisted json object from disk: loading a file with a bad checksum]
> siad v1.5.7
> Git Revision ✗-031dcde1f
> Loading...
> (1/8) Loading siad...
> (2/8) Loading gateway...
> (3/8) Loading consensus...
> (4/8) Loading transaction pool...
> (5/8) Loading wallet...
> (6/8) Loading host...
> (7/8) Loading renter...
> ERROR: [server is unable to create the Sia node; unable to create renter; unable to read persisted json object from disk: loading a file with a bad checksum]
> [server is unable to create the Sia node; unable to create renter; unable to read persisted json object from disk: loading a file with a bad checksum]
> siad v1.5.7
> Git Revision ✗-031dcde1f
> Loading...
> (1/8) Loading siad...
> (2/8) Loading gateway...
> (3/8) Loading consensus...
> (4/8) Loading transaction pool...
> (5/8) Loading wallet...
> (6/8) Loading host...
> panic: Consensus change series appears to be inconsistent - we are applying the wrong block. pid: 00000000000000000f468adb65d7e8fcc7286b68ecf27b10c4d2dbea930735ea recent: c33822505929f82cc0a04ca5de2460f717cc34feb2ed05cb3e09e10a2bb9936e
> 
> goroutine 63 [running]:
> go.sia.tech/siad/modules/transactionpool.(*TransactionPool).ProcessConsensusChange(0xc000082c00, 0xa4ea12279977d8d3, 0x3a9cb3ba2a863a48, 0xb0b51f3f0d81e680, 0x3e486f77668274ba, 0x52f5c, 0x0, 0x0, 0x0, 0xc002510f00, ...)
> 	/root/.HandyHost/siaRepo/modules/transactionpool/update.go:229 +0x2cf0
> go.sia.tech/siad/modules/consensus.(*ConsensusSet).managedInitializeSubscribe.func2(0xc0000fe0e0, 0x0, 0xc0000fe0e0)
> 	/root/.HandyHost/siaRepo/modules/consensus/subscribe.go:212 +0x315
> gitlab.com/NebulousLabs/bolt.(*DB).View(0xc000138800, 0xc000149ca8, 0x0, 0x0)
> 	/root/go/pkg/mod/gitlab.com/!nebulous!labs/bolt@v1.4.4/db.go:730 +0x93
> go.sia.tech/siad/modules/consensus.(*ConsensusSet).managedInitializeSubscribe(0xc00016cb00, 0xf7fe40, 0xc000082c00, 0xd0e8becc228b8aac, 0x14436fa54faee964, 0xdabd933114fd477e, 0x1ee7ff8c0f29b670, 0xc000169d40, 0x0, 0x0, ...)
> 	/root/.HandyHost/siaRepo/modules/consensus/subscribe.go:200 +0x325
> go.sia.tech/siad/modules/consensus.(*ConsensusSet).ConsensusSetSubscribe(0xc00016cb00, 0xf7fe40, 0xc000082c00, 0xd0e8becc228b8aac, 0x14436fa54faee964, 0xdabd933114fd477e, 0x1ee7ff8c0f29b670, 0xc000169d40, 0x0, 0x0)
> 	/root/.HandyHost/siaRepo/modules/consensus/subscribe.go:256 +0x10a
> go.sia.tech/siad/modules/transactionpool.(*TransactionPool).initPersist.func4(0xc000082c00, 0xd0e8becc228b8aac, 0x14436fa54faee964, 0xdabd933114fd477e, 0x1ee7ff8c0f29b670)
> 	/root/.HandyHost/siaRepo/modules/transactionpool/persist.go:183 +0x9f
> created by go.sia.tech/siad/modules/transactionpool.(*TransactionPool).initPersist
> 	/root/.HandyHost/siaRepo/modules/transactionpool/persist.go:182 +0xd7d
> siad v1.5.7
> Git Revision ✗-031dcde1f
> Loading...
> (1/8) Loading siad...
> (2/8) Loading gateway...
> (3/8) Loading consensus...
> (4/8) Loading transaction pool...
> (5/8) Loading wallet...
> (6/8) Loading host...
> (7/8) Loading renter...
> ERROR: [server is unable to create the Sia node; unable to create renter; unable to read persisted json object from disk: loading a file with a bad checksum]
> [server is unable to create the Sia node; unable to create renter; unable to read persisted json object from disk: loading a file with a bad checksum]
> siad v1.5.7
> Git Revision ✗-031dcde1f
> Loading...
> (1/8) Loading siad...
> (2/8) Loading gateway...
> (3/8) Loading consensus...
> (4/8) Loading transaction pool...
> (5/8) Loading wallet...
> (6/8) Loading host...
> (7/8) Loading renter...
> ERROR: [server is unable to create the Sia node; unable to create renter; unable to read persisted json object from disk: loading a file with a bad checksum]
> [server is unable to create the Sia node; unable to create renter; unable to read persisted json object from disk: loading a file with a bad checksum]
> siad v1.5.7
> Git Revision ✗-031dcde1f
> Loading...
> (1/8) Loading siad...
> (2/8) Loading gateway...
> (3/8) Loading consensus...
> (4/8) Loading transaction pool...
> (5/8) Loading wallet...
> (6/8) Loading host...
> panic: runtime error: index out of range [4503603845672960] with length 281474976710655
> 
> goroutine 10 [running]:
> gitlab.com/NebulousLabs/bolt.(*DB).page(...)
> 	/root/go/pkg/mod/gitlab.com/!nebulous!labs/bolt@v1.4.4/db.go:891
> gitlab.com/NebulousLabs/bolt.(*Tx).page(...)
> 	/root/go/pkg/mod/gitlab.com/!nebulous!labs/bolt@v1.4.4/tx.go:618
> gitlab.com/NebulousLabs/bolt.(*node).spill(0xc0045049a0, 0x0, 0x0)
> 	/root/go/pkg/mod/gitlab.com/!nebulous!labs/bolt@v1.4.4/node.go:359 +0x6f5
> gitlab.com/NebulousLabs/bolt.(*node).spill(0xc00b9ed3b0, 0x0, 0x0)
> 	/root/go/pkg/mod/gitlab.com/!nebulous!labs/bolt@v1.4.4/node.go:346 +0xba
> gitlab.com/NebulousLabs/bolt.(*node).spill(0xc003db04d0, 0x0, 0x0)
> 	/root/go/pkg/mod/gitlab.com/!nebulous!labs/bolt@v1.4.4/node.go:346 +0xba
> gitlab.com/NebulousLabs/bolt.(*node).spill(0xc0033402a0, 0xc003d8c3f0, 0xc00034cbd8)
> 	/root/go/pkg/mod/gitlab.com/!nebulous!labs/bolt@v1.4.4/node.go:346 +0xba
> gitlab.com/NebulousLabs/bolt.(*Bucket).spill(0xc003d88f40, 0xc00034cc00, 0xd)
> 	/root/go/pkg/mod/gitlab.com/!nebulous!labs/bolt@v1.4.4/bucket.go:570 +0x49a
> gitlab.com/NebulousLabs/bolt.(*Bucket).spill(0xc002e71dd8, 0x1b07980a3, 0x14b47e0)
> 	/root/go/pkg/mod/gitlab.com/!nebulous!labs/bolt@v1.4.4/bucket.go:537 +0x3f6
> gitlab.com/NebulousLabs/bolt.(*Tx).Commit(0xc002e71dc0, 0x0, 0x0)
> 	/root/go/pkg/mod/gitlab.com/!nebulous!labs/bolt@v1.4.4/tx.go:160 +0xe8
> gitlab.com/NebulousLabs/bolt.(*DB).Update(0xc000154800, 0xc00034d138, 0x0, 0x0)
> 	/root/go/pkg/mod/gitlab.com/!nebulous!labs/bolt@v1.4.4/db.go:706 +0x105
> go.sia.tech/siad/modules/consensus.(*ConsensusSet).managedAcceptBlocks(0xc00018eb00, 0xc006c46000, 0xa, 0xa, 0x0, 0x0, 0x0)
> 	/root/.HandyHost/siaRepo/modules/consensus/accept.go:247 +0x44b
> go.sia.tech/siad/modules/consensus.(*ConsensusSet).managedReceiveBlocks(0xc00018eb00, 0xf99818, 0xc000144020, 0x0, 0x0)
> 	/root/.HandyHost/siaRepo/modules/consensus/synchronize.go:225 +0x549
> go.sia.tech/siad/modules/gateway.(*Gateway).managedRPC(0xc00018c6c0, 0xc00012edc8, 0x12, 0xe231fa, 0xa, 0xc0001122b0, 0x0, 0x0)
> 	/root/.HandyHost/siaRepo/modules/gateway/rpc.go:70 +0x30e
> go.sia.tech/siad/modules/gateway.(*Gateway).RPC(0xc00018c6c0, 0xc00012edc8, 0x12, 0xe231fa, 0xa, 0xc0001122b0, 0x0, 0x0)
> 	/root/.HandyHost/siaRepo/modules/gateway/rpc.go:83 +0xe8
> go.sia.tech/siad/modules/consensus.(*ConsensusSet).managedInitialBlockchainDownload.func1(0xc00018eb00, 0xc00034dee8, 0xc00034de98, 0xc00034dea0, 0x0, 0x0)
> 	/root/.HandyHost/siaRepo/modules/consensus/synchronize.go:580 +0x122
> go.sia.tech/siad/modules/consensus.(*ConsensusSet).managedInitialBlockchainDownload(0xc00018eb00, 0xe2b41b, 0x11)
> 	/root/.HandyHost/siaRepo/modules/consensus/synchronize.go:601 +0x2a5
> go.sia.tech/siad/modules/consensus.consensusSetAsyncStartup(0xc00018eb00, 0x1, 0x0, 0x0)
> 	/root/.HandyHost/siaRepo/modules/consensus/consensusset.go:165 +0x326
> go.sia.tech/siad/modules/consensus.NewCustomConsensusSet.func1(0xc0002303c0, 0xc00018eb00, 0xf9f201)
> 	/root/.HandyHost/siaRepo/modules/consensus/consensusset.go:223 +0xbb
> created by go.sia.tech/siad/modules/consensus.NewCustomConsensusSet
> 	/root/.HandyHost/siaRepo/modules/consensus/consensusset.go:214 +0x139
> siad v1.5.7
> Git Revision ✗-031dcde1f
> Loading...
> (1/8) Loading siad...
> (2/8) Loading gateway...
> (3/8) Loading consensus...
> (4/8) Loading transaction pool...
> (5/8) Loading wallet...
> (6/8) Loading host...
> (7/8) Loading renter...
> ERROR: [server is unable to create the Sia node; unable to create renter; unable to read persisted json object from disk: loading a file with a bad checksum]
> [server is unable to create the Sia node; unable to create renter; unable to read persisted json object from disk: loading a file with a bad checksum]
> siad v1.5.7
> Git Revision ✗-031dcde1f
> Loading...
> (1/8) Loading siad...
> (2/8) Loading gateway...
> (3/8) Loading consensus...
> (4/8) Loading transaction pool...
> (5/8) Loading wallet...
> (6/8) Loading host...
> (7/8) Loading renter...
> ERROR: [server is unable to create the Sia node; unable to create renter; unable to read persisted json object from disk: loading a file with a bad checksum]
> [server is unable to create the Sia node; unable to create renter; unable to read persisted json object from disk: loading a file with a bad checksum]
> siad v1.5.7
> Git Revision ✗-031dcde1f
> Loading...
> (1/8) Loading siad...
> (2/8) Loading gateway...
> (3/8) Loading consensus...
> (4/8) Loading transaction pool...
> (5/8) Loading wallet...
> (6/8) Loading host...
> (7/8) Loading renter...
> ERROR: [server is unable to create the Sia node; unable to create renter; unable to read persisted json object from disk: loading a file with a bad checksum]
> [server is unable to create the Sia node; unable to create renter; unable to read persisted json object from disk: loading a file with a bad checksum]
> siad v1.5.7
> Git Revision ✗-031dcde1f
> Loading...
> (1/8) Loading siad...
> (2/8) Loading gateway...
> (3/8) Loading consensus...
> (4/8) Loading transaction pool...
> (5/8) Loading wallet...
> (6/8) Loading host...
> (7/8) Loading renter...
> ERROR: [server is unable to create the Sia node; unable to create renter; unable to read persisted json object from disk: loading a file with a bad checksum]
> [server is unable to create the Sia node; unable to create renter; unable to read persisted json object from disk: loading a file with a bad checksum]
> siad v1.5.7
> Git Revision ✗-031dcde1f
> Loading...
> (1/8) Loading siad...
> (2/8) Loading gateway...
> (3/8) Loading consensus...
> (4/8) Loading transaction pool...
> (5/8) Loading wallet...
> (6/8) Loading host...
> (7/8) Loading renter...
> ERROR: [server is unable to create the Sia node; unable to create renter; unable to read persisted json object from disk: loading a file with a bad checksum]
> [server is unable to create the Sia node; unable to create renter; unable to read persisted json object from disk: loading a file with a bad checksum]<


let me know if i need to give you anything else

**Comment by alexsmith540** [comment]
From the logs it seems like either something got corrupted in sia's consensus or maybe you ran out of disk space. Do you happen to have any partitions specific to /root, perhaps a partition < 50GB? You can run ```df -h``` to see if there are any partitions. My sia machine with funky partitions looks like ```/dev/sdb2        19G  5.7G   12G  33% /``` which for me means I have to have my sia data directory on a different partition, symlinked to /root/.HandyHost/siaData.
If this is the case I can show you how to move that around to a bigger partition. 
Alternately, if it's just corrupted I can try a test here to see about bootstrapping the consensus from a snapshot and rescanning which should hopefully fix as well.

**Comment by Supernaut90** [comment]
(5) 4TB drives with 1 big partition on each
(1) 1TB drive with 1 big partition. 

okay fingers crossed!

**Comment by alexsmith540** [comment]
Is the disk that /root/.HandyHost/siaData is located on ( / ) happen to be an SSD or is it an HDD? I'd definitely recommend using an SSD for storing the sia blockchain data in any case, much more stable and faster IO than HDD for sure.

I also just found this looking in more: https://gist.github.com/tbenz9/8066d74853ab28c23bd7bc1d3c7cdeda 
which covers quite a few panic errors from sia. In most cases it seems like you can delete the consensus db (chain data) and the transactions db which sia will rebuild on the next start of sia (and take 24-36 hours to sync the chain).

And if its a corrupted host, well yeah I unfortunately found this: https://www.reddit.com/r/siacoin/comments/iii5pl/error_panic_runtime_error_index_out_of_range/ 
Which the panic error you're running into ```panic: runtime error: index out of range [844428784177152] with length 281474976710655``` sortof looks like, but yeah let's just hope it's a consensus or transactions db corruption 🤞 

One thing that may tell us if it's a consensus or host corruption:
- check the logs in ```/root/.HandyHost/siaData/consensus/consensus.log``` 
- check the logs in ```/root/.HandyHost/siaData/transactionpool/transactionpool.log``` 
- check the logs in ```/root/.HandyHost/siaData/host/host.log```
and see if it has any horrible looking errors.
