### ISSUE TITLE
I don't see my sentinel node on sentinel apps

### ISSUE THREAD

**Issue by alyasboytigas** [HandyOSS/HandyHost#24]
Hello,

Just wondering how long should my sentinel dvpn node to be up and running? My node been running few days now. Since I started using dvpn ios apps, North America has 106 available nodes so when I run my node still 106 node it seems mine is running but can't find it on the dvpn nodes.

**Comment by alexsmith540** [comment]
I think the iOS app is still in alpha/beta stages and may not display the exact list of DVPN nodes. The android app displays the nodes much better vs ios.

**Comment by alexsmith540** [comment]
Here is the current list that I see from the sentinel CLI::
<img width="1108" alt="Screen Shot 2021-11-24 at 1 33 33 AM" src="https://user-images.githubusercontent.com/569830/143195270-b319911f-6c7a-46a5-a87b-bc7a1db2afbb.png">
<img width="1106" alt="Screen Shot 2021-11-24 at 1 34 02 AM" src="https://user-images.githubusercontent.com/569830/143195282-abb8d614-36ff-4543-9ec7-0835b99a7256.png">

**Comment by alyasboytigas** [comment]
I tried downloading the app from sentinel.co it seems not available in the US, hmm weird.. oh shoot I don't see my node on that list.

**Comment by alexsmith540** [comment]
Double check that you opened ports on your internet router port forwarding. There’s one port that needs to be TCP and the other needs to be UDP (they are labeled on the configuration page)

**Comment by alyasboytigas** [comment]
btw where do you get that list? thanks.

**Comment by alyasboytigas** [comment]
Yes ports are open both TCP and UDP as what I see on the configuration.

**Comment by alyasboytigas** [comment]
![Screenshot (265)_LI](https://user-images.githubusercontent.com/57547739/143257216-d531b951-2f1f-401b-b19d-b8ae0fcbc672.jpg)
![Screenshot (266)](https://user-images.githubusercontent.com/57547739/143257217-10c4a84d-4463-4c07-a2d0-02b5d9a5971d.png)

**Comment by alexsmith540** [comment]
Oh nice wow, looks like there's a "page 2" of results now, ha. I think I found you:
<img width="1185" alt="Screen Shot 2021-11-24 at 2 50 39 PM" src="https://user-images.githubusercontent.com/569830/143317287-61c8a38d-1e5f-4051-879f-19661e839f64.png">

**Comment by alexsmith540** [comment]
Also I'm using the Sentinel CLI Client to view the list:
https://github.com/sentinel-official/cli-client

**Comment by alyasboytigas** [comment]
> Also I'm using the Sentinel CLI Client to view the list: https://github.com/sentinel-official/cli-client

thanks.

**Comment by alyasboytigas** [comment]
> Oh nice wow, looks like there's a "page 2" of results now, ha. I think I found you: <img alt="Screen Shot 2021-11-24 at 2 50 39 PM" width="1185" src="https://user-images.githubusercontent.com/569830/143317287-61c8a38d-1e5f-4051-879f-19661e839f64.png">

woohooo...thanks man for all the help...

**Comment by alexsmith540** [comment]
Anytime, glad to help.
