### ISSUE TITLE
How to check my SIA node stats?

### ISSUE THREAD

**Issue by alyasboytigas** [HandyOSS/HandyHost#26]
Hello,

My sia been sync 5 days ago, just wondering where to check if my node is visible on the sia stats? I check here - https://siastats.info/hosts but it seems can't find my sia node here's my ip - 173.62.192.15:9982

Thanks.

**Comment by alyasboytigas** [comment]
I figured it out....I just needed to add some SIA coins...

**Comment by alexsmith540** [comment]
👍
