### ISSUE TITLE
Handshake process exited unexpectedly

### ISSUE THREAD

**Issue by joeyzwaann** [HandyOSS/HandyHost#29]
tarting DVPN Node...docker: Error response from daemon: driver failed programming external connectivity on endpoint upbeat_bassi (a3fce35c864327b041f85aaf082d2f331824b52591c99a4ad19dd6a111b5f8ff): Bind for 0.0.0.0:23673 failed: port is already allocated.

And also this one : 

2021-12-06T15:37:24Z ERR Handshake process exited unexpectedly error="signal: aborted (core dumped)"
![Schermafbeelding 2021-12-06 161623](https://user-images.githubusercontent.com/71401088/144875475-ab87bec3-eff2-40ab-af3b-2550ad4f4335.png)

**Comment by joeyzwaann** [comment]
Also there is a new error for every new server i make.

Error: listen tcp 160.119.248.72:13771: bind: cannot assign requested address

**Comment by alexsmith540** [comment]
I had the same thing happen on one of my nodes last week. Oddly enough I rebooted it a couple times and then it worked fine again. I think there was something going on with hnsd (handshake light client) syncing maybe last week-ish, even more-so during that AWS outage. You might reboot and try again and LMK if you still run into this.

**Comment by plimmplamm** [comment]
Hi, I have the same issue... Fresh install on UBUNTU.
