### ISSUE TITLE
Error: Get "http://ip-api.com/json": dial tcp 0.0.0.0:80: connect: connection refused - Starting DVPN node

### ISSUE THREAD

**Issue by ketsa** [HandyOSS/HandyHost#31]
I restarted this node, it was working fine.
Cannot get past this error and I noticed something strange on this machine.

Trying to resolve ip-api.com gets 127.0.0.1
Trying to resolve www.ip-api.com gets the correct ipv4 address.

>2021-12-10T19:39:18Z INF Reading the configuration file path=/root/.sentinelnode/config.toml
>2021-12-10T19:39:18Z INF Validating the configuration data={"chain":{"gas":200000,"gas_adjustment":1.05,"gas_prices":"0.1udvpn","id":"sentinelhub->2","rpc_address":"https://rpc.sentinel.co:443","simulate_and_execute":true},"handshake":{"enable":true,"peers":8},"keyring":{"backend":"file","from":"SentinelNode"},"node":{"interval_set_sessions":120000000000,"interval_update_sessions":6900000000000,"interval_update_status":3300000000000,"listen_on":"0.0.0.0:22875","moniker":"GVA-CH-DVPN->MCnode","price":"1000000udvpn","provider":"","remote_url":"https://xxx.xxx.xxx.xxx:22875"},"qos":{"max_peers":250}}
>2021-12-10T19:39:18Z INF Creating IPv4 pool CIDR=10.8.0.2/24
>2021-12-10T19:39:18Z INF Creating IPv6 pool CIDR=fd86:ea04:1115::2/120
>2021-12-10T19:39:18Z INF Initializing RPC HTTP client address=https://rpc.sentinel.co:443 endpoint=/websocket
>2021-12-10T19:39:18Z INF Initializing keyring backend=file name=sentinel
>2021-12-10T19:39:18Z INF Querying account address=sent1v9j9c43u2pgy7jgh0y6mnvnnm84xtku0d6qeyu
>Starting DVPN Node...2021-12-10T19:39:18Z INF Fetching GeoIP location info...
>Error: Get "http://ip-api.com/json": dial tcp 0.0.0.0:80: connect: connection refused

>DVPN NODE STOPPED

I do not know what logs I should include, please excuse the noobness, I have time on my hands and will provide on request.

**Comment by alexsmith540** [comment]
All good. I think this is due to the speedtest API that DVPN uses internally. Judging by the time of this it very well could have been during that massive AWS outage last week. Are you still running into this issue?

**Comment by ketsa** [comment]
I still have this problem.
Updated just now to latest 0.51 Handyhost version : Same error.

**Comment by timrettop** [comment]
@ketsa maybe your local dns is blocking the request? From a couple hosts with different dns, I get the correct IP when looking up ip-api.com and www.ip-api.com.
You could override dns by entering a manual entry in your hosts file.  Their documentation indicates that using ip-api.com is appropriate use.

**Comment by ketsa** [comment]
Doesn't look like a DNS issue, or maybe internal to the docker. I do not know docker...

`matt@T430:~$ dig ip-api.com

; <<>> DiG 9.16.1-Ubuntu <<>> ip-api.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 14100
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;ip-api.com.                    IN      A

;; ANSWER SECTION:
ip-api.com.             0       IN      A       208.95.112.1

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Mo Dez 20 13:26:11 CET 2021
;; MSG SIZE  rcvd: 55

matt@T430:~$
`

resolvectl :

`matt@T430:~$ resolvectl
Global
       LLMNR setting: no
MulticastDNS setting: no
  DNSOverTLS setting: no
      DNSSEC setting: no
    DNSSEC supported: no
          DNSSEC NTA: 10.in-addr.arpa
                      16.172.in-addr.arpa
                      168.192.in-addr.arpa
                      17.172.in-addr.arpa
                      18.172.in-addr.arpa
                      19.172.in-addr.arpa
                      20.172.in-addr.arpa
                      21.172.in-addr.arpa
                      22.172.in-addr.arpa
                      23.172.in-addr.arpa
                      24.172.in-addr.arpa
                      25.172.in-addr.arpa
                      26.172.in-addr.arpa
                      27.172.in-addr.arpa
                      28.172.in-addr.arpa
                      29.172.in-addr.arpa
                      30.172.in-addr.arpa
                      31.172.in-addr.arpa
                      corp
                      d.f.ip6.arpa
                      home
                      internal
                      intranet
                      lan
                      local
                      private
                      test

Link 4 (docker0)
      Current Scopes: none
DefaultRoute setting: no
       LLMNR setting: yes
MulticastDNS setting: no
  DNSOverTLS setting: no
      DNSSEC setting: no
    DNSSEC supported: no

Link 3 (wlp3s0)
      Current Scopes: none
DefaultRoute setting: no
       LLMNR setting: yes
MulticastDNS setting: no
  DNSOverTLS setting: no

matt@T430:~$
matt@T430:~$
matt@T430:~$
matt@T430:~$
matt@T430:~$ sudo resolvectl
Global
       LLMNR setting: no
MulticastDNS setting: no
  DNSOverTLS setting: no
      DNSSEC setting: no
    DNSSEC supported: no
          DNSSEC NTA: 10.in-addr.arpa
                      16.172.in-addr.arpa
                      168.192.in-addr.arpa
                      17.172.in-addr.arpa
                      18.172.in-addr.arpa
                      19.172.in-addr.arpa
                      20.172.in-addr.arpa
                      21.172.in-addr.arpa
                      22.172.in-addr.arpa
                      23.172.in-addr.arpa
                      24.172.in-addr.arpa
                      25.172.in-addr.arpa
                      26.172.in-addr.arpa
                      27.172.in-addr.arpa
                      28.172.in-addr.arpa
                      29.172.in-addr.arpa
                      30.172.in-addr.arpa
                      31.172.in-addr.arpa
                      corp
                      d.f.ip6.arpa
                      home
                      internal
                      intranet
                      lan
                      local
                      private
                      test

Link 4 (docker0)
      Current Scopes: none
DefaultRoute setting: no
       LLMNR setting: yes
MulticastDNS setting: no
  DNSOverTLS setting: no
      DNSSEC setting: no
    DNSSEC supported: no

Link 3 (wlp3s0)
      Current Scopes: none
DefaultRoute setting: no
       LLMNR setting: yes
MulticastDNS setting: no
  DNSOverTLS setting: no
      DNSSEC setting: no
    DNSSEC supported: no

Link 2 (enp0s25)
      Current Scopes: DNS
DefaultRoute setting: yes
       LLMNR setting: yes
MulticastDNS setting: no
  DNSOverTLS setting: no
      DNSSEC setting: no
    DNSSEC supported: no
  Current DNS Server: 192.168.0.250
         DNS Servers: 192.168.0.250
                      1.1.1.1
                      fdaa:bbcc:ddee:0:fa08:4fff:fe27:2f25
          DNS Domain: ~.
                      home
`

Don't know...

**Comment by ketsa** [comment]
I think I will reinstall from scratch. A backup config button would be nice :)

**Comment by ketsa** [comment]
from handyhost.log :  

```
HandyHost Daemon Running at: http://:8008/, and https://:58008/ (self-signed cert)
HandyHost versionData { latest: 'v0.5.1', local: 'v0.5.1', isUpToDate: true }
check machine status dvpn
node port 22875
should start dvpn { node: '22875', wireguard: '28503' }
HandyHost versionData { latest: 'v0.5.1', local: 'v0.5.1', isUpToDate: true }
ip range  192.168.0.0/24
rule val [
  'exec',
  '-i',
  'handyhost-dvpn-node',
  'sh',
  '-c',
  '"iptables -I FORWARD -i wg0 -d 192.168.0.0/24 -j REJECT"'
]
rule stderr Error: No such container: handyhost-dvpn-node
```

**Comment by alexsmith540** [comment]
Looks like docker didn’t build the image perhaps. can you run:
sudo docker image ls
And see if it lists an image for dvpn?

**Comment by ketsa** [comment]
I reinstalled everything from scratch. Ubuntu 20.04 and Handyhost and was getting the same error message !

Finally found the error was related to my pihole dns adblocker... I bypassed it and now it works. Strange.

Looks like I lost all subs - but I'm back online !!
