### ISSUE TITLE
installing akash

### ISSUE THREAD

**Issue by alyasboytigas** [HandyOSS/HandyHost#32]
Getting errors while installing akash node don't what to do.

sorry i just took pictures. see attach
![263380726_442147834119455_7120645842098514048_n](https://user-images.githubusercontent.com/57547739/145653151-a478171f-353d-46e9-8cc7-d939542a2f71.jpg)
![262845784_1040233830160206_2144629185691877308_n](https://user-images.githubusercontent.com/57547739/145653157-37356293-cfa9-4cf6-81d4-a30eb0bca5ce.jpg)
.

**Comment by alyasboytigas** [comment]
despite with the errors I check my akash node seems fine but I'm stuck on create registration when I submit I get this error.

ERROR: Error: rpc error: code = NotFound desc = account akash1wsk46ascfrw3wh4axrpccluq468qhgymzwe0jw not found: key not found

**Comment by alyasboytigas** [comment]
created new wallet getting new error - ERROR: Error: error unmarshalling: invalid character '<' looking for beginning of value

**Comment by alexsmith540** [comment]
^^ seems like some RPC errors. I have been seeing more and more rpc errors lately from akash nodes 🤦 
I just pushed out a new release v0.5.1 and ditched any of the (more) problematic rpc nodes so you may have better luck now. 
Did you end up getting that usb install working too?

**Comment by alyasboytigas** [comment]
Alex is back! I know you guys are busy. thanks for replying. Yes inspite with the errors I have received AKT is working I think. I dont have AKT yet so once I load AKT we'll see and let you know.
