### ISSUE TITLE
access denied

### ISSUE THREAD

**Issue by imap30** [HandyOSS/HandyHost#33]
Error: Unable to find image 'sentinel-dvpn-node:latest' locally docker: Error response from daemon: pull access denied for sentinel-dvpn-node, repository does not exist or may require 'docker login': denied: requested access to the resource is denied. See 'docker run --help'.

**Comment by alexsmith540** [comment]
Sounds like a docker issue we were seeing for Ubuntu on raspberry pi 4. If you are on a raspberry pi can you try this:
https://github.com/HandyOSS/HandyHost/issues/16#issuecomment-968204837

**Comment by imap30** [comment]
thanks
