### ISSUE TITLE
handyhost sentinel node getting very low speed on speedtest

### ISSUE THREAD

**Issue by syahpian** [HandyOSS/HandyHost#37]
problem description: very low speed on speedtest when starting up node 

version: HandyHost v0.5.1

operation system use: Ubuntu Server 21.10

screenshot

node speedtest result after startup
![image](https://user-images.githubusercontent.com/12189144/147848162-58c60e36-08b4-4c73-8a46-b81997499bed.png)

current internet speed
![image](https://user-images.githubusercontent.com/12189144/147848171-4562ffb8-7748-48d8-85f4-d04a2f790fbd.png)

**Comment by alexsmith540** [comment]
Yeah I think it ultimately comes down to the speedtest API that dvpn uses under the hood. It runs one test when you spin up the node and the speed test values have been hit or miss in my opinion. Really HandyHost is just displaying what DVPN tells us the speed test result is and it's nothing we can change or control. I'd suggest if it's an ongoing issue to post in the sentinel-dvpn github and see if they have any ideas.
