### ISSUE TITLE
Error when installing in Linux Mint

### ISSUE THREAD

**Issue by Goncalo7791** [HandyOSS/HandyHost#4]
Hi, when trying to install i get the following error:
"
Err:15 https://download.docker.com/linux/ubuntu ulyssa Release
  404  Not Found [IP: 13.225.242.54 443]
"

![Screenshot from 2021-10-08 09-59-35](https://user-images.githubusercontent.com/92152948/136531041-f6381ed0-9e1f-4201-af9e-b74b64c2d7fc.png)

**Comment by vocaloidat** [comment]
I also encountered the same problem. I don't know if my country blocked ip or domain name.
