### ISSUE TITLE
Price too high, not bidding 

### ISSUE THREAD

**Issue by avolon42x** [HandyOSS/HandyHost#43]
Got my Akash cluster running. Was trying to deploy with Akashlytics to my node, but I always get a "Price too high, not bidding " log entry. I can see the pricing and no matter what I set at the provider start up I never get to bid. 
Any ideas where to look?

**Comment by avolon42x** [comment]
I'm not sure, but could here be the problem:
https://github.com/HandyOSS/HandyHost/blob/0394458094ce6be82687aa44bf43791d3a058dbf/aktAPI/Marketplace.js#L357

if there is no "deposit" it becomes 50 AKT (50'000'000uakt)..where is the deposit coming from? Default is 5 AKT?

**Comment by avolon42x** [comment]
Or the problem is here
https://github.com/HandyOSS/HandyHost/blob/b4ba01c7b4c9e1cb0fdbafd155ea0e0be073025f/aktAPI/runProvider.sh#L18

there is no "uakt" as in the fee section.
I'm wild guessing here..

**Comment by avolon42x** [comment]
Ok, think I solve the puzzle. 
On the UI where you start the provider you have to enter a fraction for the per CPU pricing. So instead "1" you will have to enter "0.001" for a 1..

Can you fix this in the next update?
Thx

**Comment by avolon42x** [comment]
Enhancement -> Could you also implement scaling options on the UI?

--bid-price-cpu-scale 0.0011 \
--bid-price-memory-scale 0.0002 \
--bid-price-storage-scale 0.00009 \

https://discord.com/channels/747885925232672829/771909807359262751/928297098447835167

**Comment by alyasboytigas** [comment]
> On the UI where you start the provider you have to enter a fraction for the per CPU pricing. So instead "1" you will have to enter "0.001" for a 1..

Thanks for the tip although my akash node still not working. I'll keep this in mind.

**Comment by alexsmith540** [comment]
> Ok, think I solve the puzzle. On the UI where you start the provider you have to enter a fraction for the per CPU pricing. So instead "1" you will have to enter "0.001" for a 1..
> 
> Can you fix this in the next update? Thx

Ah yep you figured it out. Yeah it definitely makes sense to go to uakt per CPU versus uakt per mCPU as it is now because you'll always end up with 0.001 for 1uakt:cpu, thanks for the feedback.
I'll look into adding the other scaling options as well. Might not make the cut for 0.5.2 but for sure 0.5.3.

**Comment by avolon42x** [comment]
Thx. You want me to make an improvement ticket? Happy to assist..

**Comment by avolon42x** [comment]
fixed in 0.5.3
