### ISSUE TITLE
Cancel on bid is stuck

### ISSUE THREAD

**Issue by avolon42x** [HandyOSS/HandyHost#45]
Tried to cancel a running bid but it did not get canceled. Stuck in "submitting cancel"
<img width="810" alt="Screenshot 2022-01-05 at 21 53 43" src="https://user-images.githubusercontent.com/1194459/148287956-86e04518-d381-4f3d-b725-c0a3fa6614b4.png">

**Comment by alyasboytigas** [comment]
Looks like akash has a lot of problem setting up.

**Comment by alexsmith540** [comment]
Yeah akash RPC errors have been like 50|50 or more lately. I'm testing out a new build that should alleviate a ton of the RPC errors we are seeing.

**Comment by avolon42x** [comment]
Doesn‘t look like only a rpc problem. You can submit the cancel also without pw. No error gets shown, just hangs.

**Comment by alexsmith540** [comment]
ok i tracked this down, thanks the heads up. This will also go out in v0.5.2. Finishing testing tonight, should release in the next couple days.

**Comment by alexsmith540** [comment]
Fixed in v0.5.2
