### ISSUE TITLE
error requesting account cmp=client/broadcaster err="post failed: Post \"http://rpc-1.handyhost.computer:26657\": EOF"

### ISSUE THREAD

**Issue by avolon42x** [HandyOSS/HandyHost#46]
Seeing those in regular occasions in my log. I understood you added some RPC nodes, but the this error looks odd? Anything I can provide more to debug?

**Comment by alexsmith540** [comment]
Been seeing a lot of RPC errors here too, hopefully the new akash build we're working on will fix a lot of this. Luckily for the akash provider end it eventually tries new rpc nodes so for now it's ok to see rpc failures in the provider logs.

**Comment by avolon42x** [comment]
Welcome back, happy 2022! Yeah - being patient helps I found out.. great to hear that another build will come soon. Looking forward to test it out.
