### ISSUE TITLE
Cluster config - Unchecking "Is compute node" gets reverted on safe

### ISSUE THREAD

**Issue by avolon42x** [HandyOSS/HandyHost#48]
Unchecking the "is compute node" gets reverted on saving the config.

**Comment by alexsmith540** [comment]
Oops UI bug, I just fixed this in my local v0.5.2 build I'm testing. I'm running a few more long-running tests next couple of days but seems to be buttoned up. Thanks for the heads up.

**Comment by alexsmith540** [comment]
Fixed in v0.5.2
