### ISSUE TITLE
Access dVPN node externally not protected

### ISSUE THREAD

**Issue by NLatuny** [HandyOSS/HandyHost#5]
I have installed handyhost_v0.4.8.deb through CLI on my server. Everything went successful and got this message back at the end after install: `HandyHost is  now running on: http://localhost:8008`

I opened the 8008 port through ufw and went to "http://public_server_ip:8008"

I could configure the node and start it. Everything is fine. However anybody knowing my public IP from my node can now access that admin page and change my node settings.

Would be good to have this page protected in some wait, password that the installation creates and that can be adjusted after login?

**Comment by alexsmith540** [comment]
If you have it installed on ubuntu server on your local network:
```ifconfig``` on the ubuntu server to get your local IP (ex: 192.168.0.18) and then visit http://192.168.0.18:8008 (or :58008)

If you had it on ubuntu server on a vps/etc cloud:
A. In their firewall manager you'd need to whitelist you own IP for access to the machine, then visit (ideally) https://<vps-ip-address>:58008 or http://<vps-ip-address>:8008. 
B. You could likely ssh tunnel and forward 8008 to your local machine. 

In any case I thought on it for a minute and decided that I'll just setup a single access password whether locally or not. I cant assume folks will see something in the readme about not opening the management ports to the world.

**Comment by alexsmith540** [comment]
FYI Just pushed v0.4.9 which adds authentication. Instrutions on setting up here: https://github.com/HandyOSS/HandyHost#auth
