### ISSUE TITLE
Insufficient capacity for reservation even though there is plenty of

### ISSUE THREAD

**Issue by avolon42x** [HandyOSS/HandyHost#51]
I was doing some test deployments and found out, that for some reason the available capacity seems to be not take into account properly. Any idea?

I[2022-01-17|16:35:52.809] requesting reservation                       module=bidengine-order order=akash1xtd4fxgutg6hur4sq4lgd8a5w60a9xppucgf8x/4331826/1/1
D[2022-01-17|16:35:52.810] reservation requested                        module=provider-cluster cmp=service cmp=inventory-service order=akash1xtd4fxgutg6hur4sq4lgd8a5w60a9xppucgf8x/4331826/1/1 resources="group_id:<owner:\"akash1xtd4fxgutg6hur4sq4lgd8a5w60a9xppucgf8x\" dseq:4331826 gseq:1 > state:open group_spec:<name:\"dcloud\" requirements:<signed_by:<> attributes:<key:\"host\" value:\"akash\" > > **resources:<resources:<cpu:<units:<val:\"1000\" > > memory:<quantity:<val:\"2147483648\" > > storage:<quantity:<val:\"34359738368\" >** > endpoints:<> endpoints:<kind:RANDOM_PORT > endpoints:<kind:RANDOM_PORT > endpoints:<kind:RANDOM_PORT > endpoints:<kind:RANDOM_PORT > > count:1 price:<denom:\"uakt\" amount:\"100\" > > > created_at:4331827 "
I[2022-01-17|16:35:52.811] **insufficient capacity for reservation**        module=provider-cluster cmp=service cmp=inventory-service order=akash1xtd4fxgutg6hur4sq4lgd8a5w60a9xppucgf8x/4331826/1/1
E[2022-01-17|16:35:52.812] reserving resources                          module=bidengine-order order=akash1xtd4fxgutg6hur4sq4lgd8a5w60a9xppucgf8x/4331826/1/1 err="insufficient capacity"
I[2022-01-17|16:35:52.812] shutting down                                module=bidengine-order order=akash1xtd4fxgutg6hur4sq4lgd8a5w60a9xppucgf8x/4331826/1/1
D[2022-01-17|16:35:54.959] running check                                module=provider-cluster cmp=service cmp=deployment-manager lease=akash1cumcyc5wkdjank82qgh6h967jnr72kawmt0utp/4308865/1/1/akash1u5cdg7k3gl43mukca4aeultuz8x2j68mgwn28e manifest-group=akash cmp=deployment-monitor attempt=1
I[2022-01-17|16:35:54.986] check result                                 module=provider-cluster cmp=service cmp=deployment-manager lease=akash1cumcyc5wkdjank82qgh6h967jnr72kawmt0utp/4308865/1/1/akash1u5cdg7k3gl43mukca4aeultuz8x2j68mgwn28e manifest-group=akash cmp=deployment-monitor ok=true attempt=1
D[2022-01-17|16:35:54.987] reservation status update                    module=provider-cluster cmp=service cmp=inventory-service order=akash1cumcyc5wkdjank82qgh6h967jnr72kawmt0utp/4308865/1/1 resource-group=akash allocated=true
I[2022-01-17|16:35:55.575] syncing sequence                             cmp=client/broadcaster local=953 remote=953
D[2022-01-17|16:35:56.406] running check                                module=provider-cluster cmp=service cmp=deployment-manager lease=akash1xtd4fxgutg6hur4sq4lgd8a5w60a9xppucgf8x/4331431/1/1/akash1u5cdg7k3gl43mukca4aeultuz8x2j68mgwn28e manifest-group=dcloud cmp=deployment-monitor attempt=1
I[2022-01-17|16:35:56.430] check result                                 module=provider-cluster cmp=service cmp=deployment-manager lease=akash1xtd4fxgutg6hur4sq4lgd8a5w60a9xppucgf8x/4331431/1/1/akash1u5cdg7k3gl43mukca4aeultuz8x2j68mgwn28e manifest-group=dcloud cmp=deployment-monitor ok=true attempt=1
D[2022-01-17|16:35:56.431] reservation status update                    module=provider-cluster cmp=service cmp=inventory-service order=akash1xtd4fxgutg6hur4sq4lgd8a5w60a9xppucgf8x/4331431/1/1 resource-group=dcloud allocated=true
D[2022-01-17|16:36:01.583] inventory fetched                            module=provider-cluster cmp=service cmp=inventory-service nodes=3
D[2022-01-17|16:36:01.583] node resources                               module=provider-cluster cmp=service cmp=inventory-service node-id=akash-demonic-easy-insurance.fritz.box available-**cpu="units:<val:\"7195\" > attributes:<key:\"arch\" value:\"amd64\" > " available-memory="quantity:<val:\"15815972864\" > " available-storage="quantity:<val:\"473546652912\" > "
D[2022-01-17|16:36:01.584]** node resources                               module=provider-cluster cmp=service cmp=inventory-service node-id=akash-hysterical-disgusting-record.fritz.box available-**cpu="units:<val:\"3525\" > attributes:<key:\"arch\" value:\"amd64\" > " available-memory="quantity:<val:\"1054713856\" > " available-storage="quantity:<val:\"433884798224\" >** "
D[2022-01-17|16:36:01.584] node resources                               module=provider-cluster cmp=service cmp=inventory-service node-id=akash-staking-lowly-amount.fritz.box available-cpu="units:<val:\"880\" > attributes:<key:\"arch\" value:\"amd64\" > " available-memory="quantity:<val:\"1212940288\" > " available-storage="quantity:<val:\"949280873744\" > "

**Comment by alexsmith540** [comment]
I have seen this from time to time as well but can't figure out just why it happens. In addition to having more than enough physical capacity, the provider starts with up to 1000 ports so it can't be a port allocation limit either. Definitely nothing we have any control over from the provider end it seems 😢

**Comment by avolon42x** [comment]
ok thx.
