### ISSUE TITLE
Q: Akash - login to nodes possible?

### ISSUE THREAD

**Issue by avolon42x** [HandyOSS/HandyHost#52]
Is it possible to login to the nodes that get created with the usb-seeding?
I wanted to see some system stats like temps, etc.

**Comment by alyasboytigas** [comment]
not trying to hijack your post or anything. do you have your akash up and running? they’re probably busy with the updates and still for that. hoping for the next update i’ll get mine up and running.

**Comment by avolon42x** [comment]
yep, it's up and running.

**Comment by alexsmith540** [comment]
> Is it possible to login to the nodes that get created with the usb-seeding? I wanted to see some system stats like temps, etc.

Yes. Password ssh access is not possible, but the root user has an ssh key that will allow access. You can get in like:
```ssh -i ~/.ssh/handyhost ansible@some.ip.address```

**Comment by alexsmith540** [comment]
> not trying to hijack your post or anything. do you have your akash up and running? they’re probably busy with the updates and still waiting for that. hoping for the next update i’ll get mine up and running.

Good news: I'm finishing up testing tonight and will have 0.5.2 out in the next couple days. Thanks for the patience, there were a lot of moving parts going into this release.. hefty diff with +1235, -644 lines of code: https://github.com/HandyOSS/HandyHost/compare/feature_akash_aggregates_0.5.2

**Comment by avolon42x** [comment]
Worked. Thx for the tremendous work.
