### ISSUE TITLE
Unable to find image 'sentinel-dvpn-node:latest' locally

### ISSUE THREAD

**Issue by NLatuny** [HandyOSS/HandyHost#55]
After getting the known RPC issue, I restarted the node through the HandyHost dashboard. After which this error came instead:

```
Unable to find image 'sentinel-dvpn-node:latest' locally
docker: Error response from daemon: pull access denied for sentinel-dvpn-node, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```

Rebooting the server still results in the same error. Manually `docker pull sentinelofficial/sentinel-vpn-node directly` on my VPS works fine.

**Comment by alexsmith540** [comment]
If you ever need to reinstall the sentinel-dvpn-node docker image, you can do this to wipe the docker image:
1. sudo rm -rf /root/.HandyHost/sentinelData/dvpn-node
2. then re-install the debian installer from Releases which will rebuild the dvpn docker image
Also note all dvpn configs/etc will persist, this is just the base docker image that dvpn service runs.
Hope that helps!

**Comment by NLatuny** [comment]
Yes that did fix my issue, thanks
