### ISSUE TITLE
Handshake process exited unexpectedly error="signal: aborted (core dumped)"

### ISSUE THREAD

**Issue by esaumell** [HandyOSS/HandyHost#60]
HandyHost v0.5.2 under Ubuntu 21.10 on a Pi4 8GB

After searching on Discord and Telegram groups I found some people with the same issue.
https://discord.com/channels/436630361313640469/437014252625330186/939161402864717824

tigs, [12/4/21 6:53 PM]
Hello! :)

tigs, [12/4/21 6:55 PM]
running Handy Host - (awesome suite of software btw people!)

tigs, [12/4/21 6:56 PM]
2021-12-04T17:50:23Z ERR Handshake process exited unexpectedly error="signal: aborted (core dumped)"
2021-12-04T17:50:23Z INF Starting the Handshake process...
2021-12-04T17:50:30Z ERR Handshake process exited unexpectedly error="signal: aborted (core dumped)"
2021-12-04T17:50:30Z INF Starting the Handshake process... - and verbatim.

Steven McKie, [12/4/21 8:16 PM]
Post to the GitHub as an issue! This way we don’t have to continually assist when people have the same problems and there’s a canonical history for others to view.

You can find others searching by *error="signal: aborted (core dumped' on Sentinel Discord*

Searching for a solution I read that restarting the docker container solves the issue.
I tried 'docker restart <container id>' (I'm no docker guru) but then Sentinel complained so I rebooted and that solved it.
https://discord.com/channels/436630361313640469/437014252625330186/940023309196730429

Other users just solved it restarting the machine.

~~I think it would be nice to somehow catch that log line and restart the docker container automagically when needed.
May be an easier approach would be to just let the user restart the container from the Node Configuration page.~~

Thx

**Comment by esaumell** [comment]
Well I ran again onto the same issue, this time I couldn't solve it restarting the container neither rebooting the machine.
I just waited and it stopped logging on the Node Status page.

**Comment by esaumell** [comment]
I'm not sure where this error is coming from. It appears almost every time I reboot the machine. Simply by ignoring it, sooner or later it stops.

**Comment by difumetti** [comment]
I have the same issue. All ports open, install went smooth, I am using fiber internet.  

ERR Handshake process exited unexpectedly error="signal: aborted (core dumped)"
2022-02-24T23:23:29Z INF Starting the Handshake process...
2022-02-24T23:23:33Z ERR Handshake process exited unexpectedly error="signal: aborted (core dumped)"

**Comment by esaumell** [comment]
My setup is short of RAM and I reboot the machine every 24h and it gives that error almost every day. Just let it be. It will go off. It happen to me every day. AFAIK it only affects your DVPN clients in a way that they can't use HNS.

**Comment by difumetti** [comment]
My server has fiber internet and 256gb of ram. I have not gotten any followers or vpn requests yet. I'm assuming it is related to the error. This error should be reported as a bug and a resolution should be provided.  I have siacoin etc running with out this handy host control panel and have 0 problems. Handy host either needs to support their software or abandon it. I would have no problem paying handy for a license etc if they fixed this problem.  They should at least have a donate now button on their website,  buggy or not, they are doing what others are not.

**Comment by syahpian** [comment]
changing rpc address to "https://rpc-sentinel.itastakers.com:443" fix the core dump error for me

**Comment by difumetti** [comment]
> changing rpc address to "https://rpc-sentinel.itastakers.com:443" fix the core dump error for me

Thanks, I'll give it a try when I get home.

**Comment by patricklargen** [comment]
I dropped my price down to 50,000 and let it run for multiple days.  The console says the handshake is failing, but the dashboard shoes it connected.  But still no sessions.  I tried changing the RPC address and that didn't help either.  Thanks everyone for the ideas!  Keep em coming.

**Comment by darkpiv** [comment]
I have the same issue, running on Ubuntu Server 20.04. Restart and delete .sentinelnode is not working

**Comment by alexsmith540** [comment]
Good news: I tracked down the issue in dvpn's dockerfile and have a fix running/testing locally. I'll put together some instructions on how to rebuild the dvpn docker image this evening and get you all back online.

**Comment by alexsmith540** [comment]
I just pushed out an update (v0.5.3)!
After installing the v0.5.3 updates, you will notice a button "Rebuild DVPN Container" in the DVPN Status panel. Upon clicking it, you will spend 10-20mins rebuilding your DVPN Docker container with the patch required to fix the hideous "ERR Handshake process exited unexpectedly error=signal: aborted (core dumped)" error people had been seeing on DVPN startup.

**Comment by esaumell** [comment]
@alexsmith540 Not sure if you need more feedback. Feel free to close the issue. Thank you!
