### ISSUE TITLE
provider offline

### ISSUE THREAD

**Issue by alyasboytigas** [HandyOSS/HandyHost#65]
HIi,

Just restart both hh machine and akash node when both online it seems when starting provider it goes back offline.

I input the command: tail -n 200 /var/log/handyhost.log here's what i'm getting.

![Screenshot (232)](https://user-images.githubusercontent.com/57547739/153690245-28ce99f0-df55-44e2-aca0-1389a70acd01.png)

**Provider log:**

I[2022-02-11|20:13:36.794] using kube config file                       path=/root/.HandyHost/aktData/admin.conf

Starting Akash Provider...

I[2022-02-11|20:13:36.421] using kube config file                       path=/root/.HandyHost/aktData/admin.conf

Starting Akash Provider...

5000

###########  RESTARTING PROVIDER ###########

**Comment by alyasboytigas** [comment]
![Screenshot Capture - 2022-02-11 - 20-28-18](https://user-images.githubusercontent.com/57547739/153690865-550bf2d0-9903-42a4-a958-0e96afe78371.png)
![Screenshot Capture - 2022-02-11 - 20-28-28](https://user-images.githubusercontent.com/57547739/153690868-7e008b44-45c2-454c-9ca2-b244572ccade.png)
![Screenshot Capture - 2022-02-11 - 20-27-48](https://user-images.githubusercontent.com/57547739/153690871-1a7264a0-f394-4c51-a3d7-f45fd18a56ce.png)

**Comment by alyasboytigas** [comment]
now it's just stuck.
![Screenshot Capture - 2022-02-11 - 21-01-21](https://user-images.githubusercontent.com/57547739/153692090-96b2b9f2-fb71-4253-b395-e1ccc18a8263.png)

**Comment by alyasboytigas** [comment]
seems working now update both linux system and restart both node like 5x .. seems back to normal.

**Comment by alyasboytigas** [comment]
as of today provider doesn't work. tried restarting both machine no luck.

**Comment by avolon42x** [comment]
Hey @alyasboytigas - double check networking conditions and if you rebuild the cluster for any error messages. I also had major trouble last week (caused by a layer 8 problem..) and was not able to get my provider up and running. I suspect the major problem with the RPC nodes. Currently there are only three active (afaik) and it seems like they are overloaded. Don't give up!

**Comment by alyasboytigas** [comment]
@avolon42x thanks man! woke up this morning I see the provider is up and running. it seems something causing this but don't know what it is.... hope there will be fix ... have a good one.. thanks again ...

**Comment by avolon42x** [comment]
Can you check on your provider node if you also have two akash processes showing up?
<img width="726" alt="Screenshot 2022-02-14 at 19 21 59" src="https://user-images.githubusercontent.com/1194459/153923463-3dba84da-71ad-4ae6-b978-c11cf38bc553.png">

**Comment by alyasboytigas** [comment]
thanks how do i see this what command should input?

**Comment by avolon42x** [comment]
Sorry. Command is `top`

**Comment by alyasboytigas** [comment]
thanks man.
![Screenshot (238)](https://user-images.githubusercontent.com/57547739/153933001-a04fe6b1-13bc-40d6-920c-e0502f3840cb.png)

**Comment by avolon42x** [comment]
The view will update and you should see "Akash" popping up in the last column under "command". If you see two Akash there, try the following as `root`:
`systemctl stop handyhost`
and then 
`systemctl start handyhost`
wait like at least 5 min and check your dashboard. If all goes well your provider runs. 
With the `top` command you should only see one Akash process showing up.

**Comment by alyasboytigas** [comment]
![Screenshot Capture - 2022-02-14 - 14-54-59](https://user-images.githubusercontent.com/57547739/153936598-fa125004-4b2a-406f-8950-0839972fb0d4.png)
