### ISSUE TITLE
SIA offline

### ISSUE THREAD

**Issue by alyasboytigas** [HandyOSS/HandyHost#70]
Hello,

I have power outage today, and restarted HandyHost for some reason SIA wont go online, both DVPN and AKASH are online. I check on siastats it's offline.

I restart like 5x, did sudo systemctl restart handyhost like 5x, mount the drive and still offline. Is there anything I need to do? normally I just restart handyhost but not this time. wait to sync? it's been like 1hour.

Thanks.

**Comment by alyasboytigas** [comment]
ran tail - hope this screenshot helps:

![Screenshot (295)](https://user-images.githubusercontent.com/57547739/158077877-9715c553-0ab9-4a71-815c-c81b945d7fe6.png)
![Screenshot (296)](https://user-images.githubusercontent.com/57547739/158077882-e2c6158b-d3b4-4f88-8f29-dbd47955b8d1.png)
![Screenshot (297)](https://user-images.githubusercontent.com/57547739/158077885-af9dc56c-d6ef-4aa7-b916-b8d311895e6d.png)
![Screenshot (298)](https://user-images.githubusercontent.com/57547739/158077887-4c2f691f-00de-46ae-8292-66ba27908a7b.png)
![Screenshot (299)](https://user-images.githubusercontent.com/57547739/158077893-161b0c0c-d48c-4fcc-a86f-b27888e7dd42.png)
![Screenshot (300)](https://user-images.githubusercontent.com/57547739/158077896-d957ccdb-8e4e-4a7d-b842-2c4065d67460.png)
![Screenshot (301)](https://user-images.githubusercontent.com/57547739/158077900-49db9292-1629-4ba9-a3cf-845741f08ae6.png)

**Comment by alyasboytigas** [comment]
all SIA pages blanks
![Screenshot (306)](https://user-images.githubusercontent.com/57547739/158509864-5deb83f8-cd39-4594-b841-8d8ffc882923.png)
![Screenshot (305)](https://user-images.githubusercontent.com/57547739/158509908-223a21b2-712c-4826-9dd6-f9fe7cc82b71.png)
![Screenshot (304)](https://user-images.githubusercontent.com/57547739/158509949-57c3d286-a4f8-4e41-965d-efc9eebb4ce0.png)
![Screenshot (303)](https://user-images.githubusercontent.com/57547739/158509982-fd64e162-0a4c-42c3-b411-2e005d0e0ebc.png)
![Screenshot (307)](https://user-images.githubusercontent.com/57547739/158510031-ab61b47b-b576-49dd-9718-b8263bba6f11.png)

upgraded to v0.5.3 still no luck.

**Comment by alyasboytigas** [comment]
is there a way i can edit or command or find which file to change the network address? i also change noip hostname name. Both DVPN and AKASH working flawless.

**Comment by alyasboytigas** [comment]
siad-output.log
![Screenshot (308)](https://user-images.githubusercontent.com/57547739/158706807-3116337e-564a-4646-8ccf-10a006341691.png)

**Comment by alexsmith540** [comment]
There are sia daemon logs at /root/.HandyHost/siaData/siad-output.log
Those logs will help diagnose what’s going on with sia. Sometimes I have had sia take up to a few hours to sync after an unexpected outage.
