### ISSUE TITLE
No Configuration Found after adding nodes

### ISSUE THREAD

**Issue by freakinfofa** [HandyOSS/HandyHost#72]
good evening,

after i tried adding 2 additional nodes to the cluster for a total of 7 nodes, i get the "No Configuration Found" in the dashboard, my configuration settings gone and the two new nodes not listed.

To give a bit of more background on what i think the issue may be, I had upgraded to 5.3 the day it was available. I also used the original USB boot drive from when i first deployed the cluster.

is there any way i should have gone about adding the nodes after upgrading to a newer version? maybe creating a new usb drive for the new nodes?

should i try rebuilding the new nodes with the newly created usb and them to the current 5 node cluster? there original 5 nodes seem to still be "working their leases" since utilization shows around 80% CPU

![image](https://user-images.githubusercontent.com/85818014/158715142-23955e76-78be-439f-830e-381539927b6f.png)
![image](https://user-images.githubusercontent.com/85818014/158715411-878e2950-2ee9-4980-af03-499ce703b074.png)

**Comment by alexsmith540** [comment]
Weird issue. Curious to get to the bottom of this.
Regarding "no configuration found": can you check what your akash config contains? It's in /root/.HandyHost/aktData/clusterConfig.json
You may just have to fill in the form in the config panel again with your cluster info and possibly re-register the cluster, depends on what clusterConfig.json contains (or not). clusterConfig.json should have all the existing nodes contained in the nodes section, and also should contain all your provider details in the provider section. 

Regarding the USB drive, a couple of questions:
When you ran the usb drive did it happen to show the confirmations inside the akash app that new nodes were added? 
If not, or in any case: you may just have to rebuild the USB drive and flash those 2 new machines. In the akash configuration panel, there is a red button in the top-right that will allow you to flash the USB disk with a new iso. We made a couple of changes to the USB drive in v0.5.2 as a few of the un-attended ubuntu installation workflows seemed to have changed slightly so I'd definitely recommend re-building your USB stick if its been awhile.

**Comment by freakinfofa** [comment]
ill check the json file and report back.

And Yes, both nodes triggered the confirmation window inside the akash webapp, i was able to select them after scanning for new nodes and proceeded to build the cluster. (all config was there and not altered)
the rebuild went smooth and gave me the successfully created message. it was when i switched to the dashboard when i saw the no configuration found... I then returned to the config tab and all configuration fields were empty but my original nodes till with a blue checkmark.

**Comment by freakinfofa** [comment]
the cluster config file has the original 5 nodes information listed only and it seems correct. I haven't had a chance to flash my 2 vms with the new usb iso. ill let you know if everything works after that.

**Comment by freakinfofa** [comment]
everything is back operational after rebuilding the nodes with the new USB/ISO. but in all honesty I think i might have not rebuilt the cluster properly the first time.

this time I noticed that after adding the nodes and getting the successfully added nodes pop-ups >> re-scanned for new nodes under configuration >> checked them all fill out the configuration information (since it was blank from the previous attempt) >> then i clicked the advanced options and noticed that the new nodes were not listed there.. they showed up under advanced options after i saved the configuration.. then i was able to build the cluster with no issues and everything is working now.
