### ISSUE TITLE
Error when I try to update from Current: v0.2.8 to Latest: v0.3.0

### ISSUE THREAD

**Issue by CyderEyesX** [HandyOSS/HandyHost#74]
Starting DVPN Node Update...

DVPN NODE STOPPED
Fetching origin
error: Your local changes to the following files would be overwritten by checkout:
	Dockerfile
Please commit your changes or stash them before you switch branches.
Aborting

**Comment by alexsmith540** [comment]
FYI v0.5.4 just shipped

**Comment by CyderEyesX** [comment]
Everything working good!

**Comment by CyderEyesX** [comment]
Everything working good!
