### ISSUE TITLE
akash - Error: SQLITE_ERROR: no such table: SESSIONS

### ISSUE THREAD

**Issue by freakinfofa** [HandyOSS/HandyHost#78]
so after I overlooked the SIA folder using the entire disk crashing the whole server.. I have cloned drive to a bigger one and extended the partitions properly, but now im having issues with my akash provider. 

akash provider crashed, restart it... 2022-04-25T01:05:59.381Z
db is loaded
error querying sessions DB [Error: SQLITE_ERROR: no such table: SESSIONS] {
errno: 1,
code: 'SQLITE_ERROR'
}

any idea what could this be?

**Comment by freakinfofa** [comment]
seeing this on the logs.

localadmin@handyhost:~$ tail -100 /var/log/handyhost.log 
akash provider crashed, restart it... 2022-04-25T13:16:11.748Z
akash provider crashed, restart it... 2022-04-25T13:16:11.752Z
is positional [ 'api', 'akt', 'getClusterStats' ]
is positional [ 'api', 'akt', 'getMarketAggregates' ]
is positional [ 'api', 'akt', 'getClusterConfig' ]
is positional [ 'api', 'akt', 'getProviderParams' ]
is positional [ 'api', 'akt', 'getState' ]
akash exists?? true
akash dir exists? true
is positional [ 'api', 'getIP' ]
is positional [ 'api', 'akt', 'getClusterStats' ]
is positional [ 'api', 'akt', 'getMarketAggregates' ]
is positional [ 'api', 'akt', 'getClusterStats' ]
is positional [ 'api', 'akt', 'getMarketAggregates' ]
is positional [ 'api', 'akt', 'getClusterConfig' ]
is positional [ 'api', 'akt', 'getProviderParams' ]
is positional [ 'api', 'akt', 'getState' ]
akash exists?? true
akash dir exists? true
is positional [ 'api', 'getIP' ]
is positional [ 'api', 'akt', 'getClusterStats' ]
is positional [ 'api', 'akt', 'getMarketAggregates' ]
{"level":"error","message":"Forever detected script was killed by signal: SIGKILL"}
(node:1561) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
HandyHost Daemon Running at: http://10.9.50.11:8008/, and https://10.9.50.11:58008/ (self-signed cert)
no version, must be dead
start siad /root/.HandyHost/siaData
hostPort :9972
rpcPort :9971
muxPort :9973
muxWSPort :9974
apiPort :10801
tryingwallet unlock
status not 200 490 status code 490
status code is 490
error unlocking wallet 490
tryingwallet unlock
status not 200 490 status code 490
status code is 490
error unlocking wallet 490
tryingwallet unlock
status not 200 204 No Content
no json response
wallet unlock success
init SC health check interval
provider is closed
was timed restart false
was halted? undefined
akash crashed, try restart
akash provider crashed, restart it... 2022-04-25T13:19:09.804Z
provider is closed
was timed restart false
was halted? undefined
akash crashed, try restart
akash provider crashed, restart it... 2022-04-25T13:19:14.329Z
provider is closed
was timed restart false
was halted? undefined
akash crashed, try restart
akash provider crashed, restart it... 2022-04-25T13:19:19.484Z
provider is closed
was timed restart false
was halted? undefined
akash crashed, try restart
akash provider crashed, restart it... 2022-04-25T13:19:24.047Z
is positional [ 'api', 'akt', 'getClusterStats' ]
is positional [ 'api', 'akt', 'getMarketAggregates' ]
is positional [ 'api', 'akt', 'getClusterConfig' ]
is positional [ 'api', 'akt', 'getProviderParams' ]
is positional [ 'api', 'akt', 'getState' ]
akash exists?? true
akash dir exists? true
is positional [ 'api', 'getIP' ]
is positional [ 'api', 'akt', 'getMarketAggregates' ]
is positional [ 'api', 'akt', 'getClusterStats' ]
provider is closed
was timed restart false
was halted? undefined
akash crashed, try restart
akash provider crashed, restart it... 2022-04-25T13:19:28.638Z
provider is closed
was timed restart false
was halted? undefined
akash crashed, try restart
akash provider crashed, restart it... 2022-04-25T13:19:33.139Z
provider is closed
was timed restart false
was halted? undefined
akash crashed, try restart
akash provider crashed, restart it... 2022-04-25T13:19:37.792Z
provider is closed
was timed restart false
was halted? undefined
akash crashed, try restart
akash provider crashed, restart it... 2022-04-25T13:19:42.406Z
is positional [ 'api', 'akt', 'runProvider' ]
should akash run?  true
is positional [ 'api', 'akt', 'getClusterStats' ]
is positional [ 'api', 'akt', 'getMarketAggregates' ]

**Comment by freakinfofa** [comment]
Thanks! for both answers! I'll definitely check the akash discord.

I do not run dVPN, so basically i can disable the whole thing if possible (only sia and akash). I did run the v0.16 update, thats when i realized i was out of disk space.. whoops! I have tried rebuilding the cluster but akash provider isnt starting.

let me know if you want to see any other logs!

**Comment by alexsmith540** [comment]
Ok that probably explains it then. Akash released v0.16 a bit earlier than it’s supported on-chain. So basically 0.16 isn’t backward compatible which is why the provider won’t start. On the plus side 0.16 goes live 4/26 so we’ll have a handyhost update just after it goes live which you can run and get provider back online.

**Comment by freakinfofa** [comment]
that makes sense! :P alright ill be patiently waiting for the updates!!

Thanks again!

**Comment by alexsmith540** [comment]
FYI Akash v0.16.x rolled out and thus we pushed HandyHost v0.5.5. 
One note about migrating to v0.16 from HandyHost UI:

After running the HandyHost v0.5.5 update, you will see a button within the Akash configuration panel titled "Migrate to Akash v0.16.x". Clicking it will migrate your Akash provider (and any contracts) to the latest Akash v0.16.x CRD. Note: Akash v0.16 is a major release and will not be backward compatible with v0.14.x RPC nodes or providers so make sure to run the migration utility.

**Comment by freakinfofa** [comment]
all set! back online 100%

Thanks a lot! updates and migration went super smooth!

Closing this issue!
