### ISSUE TITLE
AKT: old chain-id

### ISSUE THREAD

**Issue by avolon42x** [HandyOSS/HandyHost#83]
I think somewhere in the provider run script there is still the old chain-id. Don't know what the impact is yet..
<img width="1113" alt="Bildschirmfoto 2022-04-28 um 16 52 19" src="https://user-images.githubusercontent.com/1194459/165781267-d3af2597-7a7a-468b-9e44-fd44918b20af.png">

Get's pulled, probably ovrclk hasn't updated the source..
https://github.com/HandyOSS/HandyHost/blob/4e52f235683be20650215e7bf4a9d1bd9c64f5e8/aktAPI/startNode.sh

**Comment by alexsmith540** [comment]
I’ll double check but I’m almost certain we source chain id as an environment variable which is loaded dynamically from 
https://github.com/ovrclk/net/blob/master/mainnet/chain-id.txt

**Comment by alexsmith540** [comment]
Ok confirmed it’s set dynamically here:
https://github.com/HandyOSS/HandyHost/blob/master/aktAPI/envUtils.js#L50

**Comment by avolon42x** [comment]
I just asked baktun of Akashlytics regarding my provider information that is not shown in Akashlytics and it look like he doesn't sees my provider there..could that be related?
<img width="661" alt="Bildschirmfoto 2022-04-28 um 18 12 21" src="https://user-images.githubusercontent.com/1194459/165797397-4958dc4c-ea54-4a83-9012-dc4197c8a132.png">

Can I hardcode the ID and restart? See what happens?

**Comment by avolon42x** [comment]
I made a post on discord - must be an error

**Comment by avolon42x** [comment]
Chain-ID does not change: https://discord.com/channels/747885925232672829/771909807359262751/968572319884771398
