### ISSUE TITLE
Usability Improvements

### ISSUE THREAD

**Issue by mando222** [HandyOSS/HandyHost#9]
Ubuntu 20.04.3 LTS
handyhost_v0.4.9

These are all usability issues that I ran into on my first few runthroughs. 

1.  Create a guided experience that has prompts for the initial setup.
2.  Rework the tiny interaction button in the top right corner into something more noticeable.
3.  Allow for changing of Gas fees from the interface
4.  Set a default cluster name as this shouldn't matter to the user.  Leave the box to configure it custom if the user wants but it needs to be seeded
5.  Clean up the bids screens so that old/invalid data doesn't intermittently show up
6.  Make a clean clear way for a wallet to be added (maybe similar to how keplr does it with a hardware wallet)
7.  Better descriptions on most input fields.
8.  For the hardware requirements have this pop up instead of being a small corner button that you could easily miss
9.  Explain the rationale behind the hardware choices so that a user can find alternative parts if availability is an issue.
10.  Break the USB drive step into a separate section from the hardware step.  There is way too much information on the single page to catch every important thing.
11.  The appearing and disappearing items on the left-hand sidebar are hard to use as they are not always present when referenced by the messages that do pop up on occasion.   Also, they should be steps in a prompt flow not on the sidebar.
12. Expose the UI without needing to log dive for the port number

**Comment by alexsmith540** [comment]
Thanks again for all the great feedback! I implemented these into v0.5.0
